### ISSUE TITLE
Feature: Add Dark Mode to the Website 🌑

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#10]
**Feature description**
Add Dark Mode to the Website 🌑

👀 Have you spent some time to check if this issue has been raised before?

- [ ]  I checked and didn't find similar issue

🏢 Have you read the Code of Conduct?

- [ ]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/5332d5a97ff58a00a86839db46c37c73e2b15842/CODE_OF_CONDUCT.md)

**Comment by SSaurabhsahuu** [comment]
Hi Shivam please assign this issue to me

**Comment by Wanderer-of-the-abyss** [comment]
Can you assign this issue to me ?

**Comment by The-Shivam-garg** [comment]
Already assigned

**Comment by rohit-raj25** [comment]
I want to work on this issue under JWOC

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by sakshamgurbhele** [comment]
This issue is being resolved in a PR, Thank You for contributing..
