### ISSUE TITLE
docs: Add Code of Conduct

### ISSUE THREAD

**Issue by Pradumnasaraf** [The-Shivam-garg/BigB-E-learn-Websit-e#101]
### Changes
- Add official `CODE_OF_CONDUCT.md` (provided by GitHub)

####  Due to that we are also missing out on some checks on the community standards checklist

![Screenshot from 2022-03-01 21-00-07](https://user-images.githubusercontent.com/51878265/156198146-17771699-c3a3-4589-8a76-fd987c5ea4bd.png)

#### Contribution towards GSsoc`22, Thank you

**Comment by The-Shivam-garg** [comment]
Thanks @Pradumnasaraf for finding the issue in documentation , you can start working on this

**Comment by Pradumnasaraf** [comment]
> Thanks @Pradumnasaraf for finding the issue in documentation , you can start working on this

Thank you :), Please provide an Email to include that in the Code of Conduct

**Comment by Pradumnasaraf** [comment]
> Thanks @Pradumnasaraf for finding the issue in documentation , you can start working on this

Thank you @The-Shivam-garg  :), Please provide an Email to include that in the Code of Conduct
