### ISSUE TITLE
Enhancement : Design a UI for Counselling Page 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#102]
![image](https://user-images.githubusercontent.com/83035995/156218884-3f529bff-3ce4-49cb-9dea-ba6218c81bd3.png)

Hey contributor,
I want you to create  a new page for counselling and make it redirecting through this Get Counselling button.

**Comment by artimanputra** [comment]
Hey, I would like to work on this issue. Can please you assign it to me?

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest but for now ,I'm assigning this issue to @artimanputra  .Till then you guys can explore the website and pre-issues that are mentioned in the issue section ,to find the issue you might be interested in working.

**Comment by sakshamgurbhele** [comment]
Hey @artimanputra, are you still on this issue?
