### ISSUE TITLE
Change the Feedback Content 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#103]
![image](https://user-images.githubusercontent.com/83035995/156219468-8f09d176-5555-49da-a697-ae6752bc0187.png)

Make it more person specific ,change the Following :
1.Name  (ex: Aman )
2.Email    (ex: aman12@gmail.com)
3.Image of person
4.Feedback (write more personalized feedbacks)

**Comment by Atif0604** [comment]
Hey @The-Shivam-garg Please assign under GSSOC'22
