### ISSUE TITLE
Enhancement : Change the UI of Feedback section.

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#104]
![image](https://user-images.githubusercontent.com/83035995/156220178-afdfbc21-907e-4b4d-a43b-844431020f6b.png)

**Comment by tanya-gupta25** [comment]
I want to work on this issue under GSSOC

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest but for now ,I'm assigning this issue to @tanya-gupta25  .Till then you guys can explore the website and pre-issues that are mentioned in the issue section ,to find the issue you might be interested in working.
