### ISSUE TITLE
Enhancement : Add the Email in the footer section.

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#105]
![image](https://user-images.githubusercontent.com/83035995/156220638-854e51ce-434b-4e86-8cb4-b222d9a67fb2.png)

Hey contributor,
I want you to add the email ,down below in the HAVE A QUESTION ? section.

##Output Preview 
**Have a Question?**
-  Exist Somewhere in BHARAT, Earth
-  1234-567-891
-  info@BigB.com
-  bigbeduwebsite@gmail.com

**Comment by TG922** [comment]
Hey! Admin I would like to work on this issue under GSSoC'22 . Please Assign me with this issue .

**Comment by Atif0604** [comment]
Hey @The-Shivam-garg Please assign under GSSOC'22

**Comment by Mohit-1909** [comment]
@The-Shivam-garg I can work on this issue faster, Can you please assign this issue to me?
