### ISSUE TITLE
Enhancement: Design the more attractive UI for the Feature page 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#108]
![image](https://user-images.githubusercontent.com/83035995/156224938-001ba711-638e-4166-ac61-4344eb2971ed.png)

**Comment by TG922** [comment]
Hey! Admin I would like to work on this issue under GSSoC'22 . Please Assign me with this issue .

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest but for now ,I'm assigning this issue to @Pragatii08  .Till then you guys can explore the website and pre-issues that are mentioned in the issue section ,to find the issue you might be interested in working.

**Comment by The-Shivam-garg** [comment]
hey @Anjuli08 you can start working on this issue

**Comment by Anjuli08** [comment]
Thank you !!
