### ISSUE TITLE
Enhancement : Change the pop-up Card Content 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#109]
![image](https://user-images.githubusercontent.com/83035995/156225173-947a341e-6b85-4e3e-a71b-2a2270ff9328.png)

**Comment by the-centinal** [comment]
please assign this task to  me under GSSOC 2022

**Comment by TG922** [comment]
Hey! Admin I would like to work on this issue under GSSoC'22 . Please Assign me with this issue .

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest but for now ,I'm assigning this issue to @the-centinal .Till then you guys can explore the website and pre-issues that are mentioned in the issue section ,to find the issue you might be interested in working.
