### ISSUE TITLE
Feature: Create the new page for the Saved option. 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#111]
![image](https://user-images.githubusercontent.com/83035995/156225837-ec5ec31f-af66-4180-870c-de1241f0b741.png)

Hey contributor,
I want you to design the page for the saved, So that people can get their saved course at one place.

**Comment by TG922** [comment]
Hey! Admin I would like to work on this issue under GSSoC'22 . Please Assign me with this issue .
