### ISSUE TITLE
Enhancement: Add custom scroll bar

### ISSUE THREAD

**Issue by TG922** [The-Shivam-garg/BigB-E-learn-Websit-e#114]
### Description

- I want to add custom scroll bar for this website.

### Screenshot

- Please assign me on this issue under GSSOC '22.

![Image](https://user-images.githubusercontent.com/70098839/156284321-2ffa2d97-7bdb-498c-bd3d-a88a87227566.PNG)

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest ,I'm assigning this issue to @TG922
