### ISSUE TITLE
Enhancement : Expanding Underlined text animation on hover

### ISSUE THREAD

**Issue by TG922** [The-Shivam-garg/BigB-E-learn-Websit-e#116]
### Description

- I want to add underlined text animation on hover for this website.

### Screenshot

- Please assign me on this issue this under GSSOC '22.

![Image](https://user-images.githubusercontent.com/70098839/156288332-2d5326ee-ac4e-46e8-a81e-2ea897dd995c.PNG)

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest  ,I'm assigning this issue to @TG922

**Comment by HarshKumarChoudary** [comment]
I'm GSSOC 22 contributor. If this issue is still available and is not completed yet, please assign it to me. Also please add GSSOC22 label for that. Thanks

**Comment by TG922** [comment]
@HarshKumarChoudary I have already done most of part but due to exam i was not able to work on it..just require to PR today.

**Comment by sakshamgurbhele** [comment]
@TG922 Hey, what's the status?

**Comment by sakshamgurbhele** [comment]
> > @TG922 Hey, what's the status?
> 
> Hey @sakshamgurbhele nice to meet you !! Actually, my Laptop fan was not working properly so, I was not able to access my laptop for long but from today I'm free to work on all issues. Tomorrow morning I will send PR regarding this !!

No worries! take your time

**Comment by TG922** [comment]
@sakshamgurbhele work is done!! Can I take any branch name??
Or is there any fixed name?? I'm ready to pull within some time today

**Comment by sakshamgurbhele** [comment]
@TG922 No, name your branch as per your choice.

**Comment by TG922** [comment]
Where is @The-Shivam-garg did he leave?? Just Asking !!

**Comment by sakshamgurbhele** [comment]
@TG922 Nope, he is busy with his exams.
