### ISSUE TITLE
Enhancement : ADD the email in the Readme.md

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#119]
![image](https://user-images.githubusercontent.com/83035995/156301717-8f2a4674-dffa-412f-aa4d-f9f631496f21.png)

Hey contributor,
I want you to add the Email id of this site in readme above the **In Development Phase** with the suitable statement.

Email: bigbeduwebsite@gmail.com

**Comment by Sandhya312** [comment]
@The-Shivam-garg  
I want to complete this issue. Please assign it to me.

**Comment by The-Arshad-Khan** [comment]
@The-Shivam-garg I'd like to Complete This Issue; Please Assign it To ME!, Under GSSOC'22

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest but for now ,I'm assigning this issue to @Sandhya312  .Till then you guys can explore the website and pre-issues that are mentioned in the issue section ,to find the issue you might be interested in working.

**Comment by Sandhya312** [comment]
> Thanks for showing interest but for now ,I'm assigning this issue to @Sandhya312 .Till then you guys can explore the website and pre-issues that are mentioned in the issue section ,to find the issue you might be interested in working.

Thank you so much for assigning me this issue.

**Comment by Sandhya312** [comment]
> Thanks for showing interest but for now ,I'm assigning this issue to @Sandhya312 .Till then you guys can explore the website and pre-issues that are mentioned in the issue section ,to find the issue you might be interested in working.

Hey @The-Shivam-garg, I update the readme.md. Please checkout the pullrequest **Update the readme.md #143**.

**Comment by sakshamgurbhele** [comment]
Thank You @Sandhya312 for your contribution, we have some more issues. feel free to comment on them too.

**Comment by Sandhya312** [comment]
> Thank You @Sandhya312 for your contribution, we have some more issues. feel free to comment on them too.

Sure
