### ISSUE TITLE
Improve footer UI

### ISSUE THREAD

**Issue by kheya19** [The-Shivam-garg/BigB-E-learn-Websit-e#120]
improving the existing design for a better feel

**Comment by The-Shivam-garg** [comment]
sure @kheya19 you can start working on this issue.

**Comment by sakshamgurbhele** [comment]
@kheya19 are you still on this issue?

**Comment by kheya19** [comment]
> @kheya19 are you still on this issue? 

I have completed this and my code have been merged

**Comment by sakshamgurbhele** [comment]
@kheya19, Can you please link your PR in this issue

**Comment by kheya19** [comment]
https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/pull/164

> @kheya19, Can you please link your PR in this issue
https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/pull/164

**Comment by sakshamgurbhele** [comment]
Thank You @kheya19 for contributing 🚀😇

**Comment by kheya19** [comment]
> Thank You @kheya19 for contributing 🚀😇

It's my pleasure to work with you
