### ISSUE TITLE
IMPROVING AND FIXING entire UI of the website 

### ISSUE THREAD

**Issue by akki251** [The-Shivam-garg/BigB-E-learn-Websit-e#121]
Hello, Shivam. back in 2020... 
I've developed and designed a number of websites and worked closely with UI/Ux designers and leads since 2020, and with that expertise, I've found several major and minor fixes and enhancements that will help BigB-e-Learn UI 
and UX reach the next level. , I'm attaching a detailed JPEG; please zoom it in to see it well, and if possible, pin this issue so that more people may work on the various issues mentioned.

![Issues](https://user-images.githubusercontent.com/67007034/156309168-1c419994-e765-4e84-bb8a-d508ce31a828.jpg)

**Comment by BabyElias** [comment]
I would also like to collaborate on this, if given a chance under GSSOC'22.

**Comment by The-Shivam-garg** [comment]
Thanks @akki251 for recommending the issue this project has, will surely concern about it. If you are interested in working on any of these issue let me know.

**Comment by akki251** [comment]
Yes, I would like to work on these two issues , Please assign it under Gssoc'22 and give atleast level-2, cause these might take time 
![image](https://user-images.githubusercontent.com/67007034/156430747-506e0e02-a1a6-4db6-9d20-c37d1788da48.png)
![image](https://user-images.githubusercontent.com/67007034/156430881-74521455-6e0c-46b9-b48c-9ba33ea61c75.png)

**Comment by The-Shivam-garg** [comment]
Sorry @akki251 this issue is already assigned to the another contributor
