### ISSUE TITLE
Feature: Create a separate new page for Events

### ISSUE THREAD

**Issue by Kumar-laxmi** [The-Shivam-garg/BigB-E-learn-Websit-e#123]
There is a link of event in footer, so I can create an link the event page.

**Comment by Kumar-laxmi** [comment]
I haven't been assigned yet

**Comment by The-Shivam-garg** [comment]
We dont need a event page.instead you can change that event with something
else in the footer which will be more relevant with the Project.

**Comment by Kumar-laxmi** [comment]
Actually you can have it like this 
![Screenshot 2022-03-03 081029](https://user-images.githubusercontent.com/76027425/156485904-49d7b8a5-131f-4d9d-88eb-9da09116a858.png)

**Comment by Kumar-laxmi** [comment]
This image is just a sample

**Comment by Kumar-laxmi** [comment]
On that you can hackathons, quizzes, or other educational competitions

**Comment by The-Shivam-garg** [comment]
Seems Cool! @Kumar-laxmi you can start working on this issue

**Comment by Kumar-laxmi** [comment]
yeah thanks
