### ISSUE TITLE
Improve layout of Text

### ISSUE THREAD

**Issue by BabyElias** [The-Shivam-garg/BigB-E-learn-Websit-e#128]
Hey @The-Shivam-garg ,I would like to improve the presentation of text on Courses page (under Courses.html file).Please assign me this issue under GSSOC'22.
![snip](https://user-images.githubusercontent.com/95405559/156375197-5696bab8-2e35-42ea-9a29-ff3e8e729b3e.PNG)

**Comment by sakshamgurbhele** [comment]
@BabyElias Thank you for contributing, ✨
