### ISSUE TITLE
Feature add a pop up message for the Lauch of New course  

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#13]

**Comment by uzumakiritam** [comment]
I want to work in this issue. Kindly assign this issue.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
Thank you all of you for showing your interest in this issue . But for now being I'm assigning this issue to @uzumakiritam  because of his earlier comment. You can explore the website .
Best wishes for your futher contribution in JWOC.😊
