### ISSUE TITLE
Enhancement: Replace former Techbenchers Logo to our new Community SideHustlers.

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#131]
![image](https://user-images.githubusercontent.com/83035995/156412370-abe9b8d2-770a-4cb6-9609-474e11b8224f.png)

**Comment by The-Arshad-Khan** [comment]
Assign This issue to me Under GSSOC'22

**Comment by The-Arshad-Khan** [comment]
THemks

**Comment by The-Shivam-garg** [comment]
Thanks @The-Arshad-Khan for  showing your interest.

**Comment by alphaayu** [comment]
can you please assign it to me

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest in this issue but the issue is already resolved . I would recommend  contributors to explore the website and issue mentioned in issue section .
