### ISSUE TITLE
Enhancement: Fix the issue in the Homepage 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#132]
![bigb1](https://user-images.githubusercontent.com/83035995/156415507-d25ba27e-8556-4aeb-854c-1cd9fc350a51.jpg)

**Comment by The-Shivam-garg** [comment]
Hey @saketsagarsingh are you still working on this issue ?

**Comment by MitAbhay** [comment]
@The-Shivam-garg  If this issue is not still resolved, can I go forward with this issue ??

**Comment by Anjuli08** [comment]
I would like to work on this issue under GSSOC '22, if not resolved yet!!!!

**Comment by The-Shivam-garg** [comment]
Hey @Anjuli08 you can start working on this issue

**Comment by Sukriti-m** [comment]
Hi @The-Shivam-garg
If this task is being delayed, then I'd be glad to work on this issue.
I'd be grateful if you could assign this task to me under GSSoC'22.

**Comment by The-Shivam-garg** [comment]
Hey @Sukriti-m you can work on this issue

**Comment by Sukriti-m** [comment]
Hey @The-Shivam-garg 
I tried to change the font-size of the text in VS code. But no changes can be seen on the page whereas when I am changing the styles using Chrome Developer Tools then it is changing.
Could you please tell me why the styles are not changing in VS code.

https://user-images.githubusercontent.com/93239528/164581721-13aa5b03-dd62-4371-87dc-003207a3f7b7.mp4

**Comment by The-Shivam-garg** [comment]
> Hey @The-Shivam-garg I tried to change the font-size of the text in VS code. But no changes can be seen on the page whereas when I am changing the styles using Chrome Developer Tools then it is changing. Could you please tell me why the styles are not changing in VS code.
> 
>  bibB.mp4

hey @Sukriti-m the active website in which you are trying to do the modification is the remote website , or its the repository website ?

**Comment by Sukriti-m** [comment]
> > Hey @The-Shivam-garg I tried to change the font-size of the text in VS code. But no changes can be seen on the page whereas when I am changing the styles using Chrome Developer Tools then it is changing. Could you please tell me why the styles are not changing in VS code.
> > bibB.mp4
> 
> hey @Sukriti-m the active website in which you are trying to do the modification is the remote website , or its the repository website ?

Firstly, I forked this project and then cloned it on my system using git clone and I am working on that only.

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?
