### ISSUE TITLE
Enhancement: Change the icon colors in the Homepage

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#133]
![bigb2](https://user-images.githubusercontent.com/83035995/156415707-e52167ff-6b88-461b-a512-d770c01417f8.jpg)

**Comment by The-Shivam-garg** [comment]
Thanks for showing the interest @saketsagarsingh ,I have assigned this issue.

**Comment by purohitmansi** [comment]
Hello @The-Shivam-garg!

I am a GSSoC22 contributor. I would love to work on this issue and make PR as soon as I resolve the issue. Please do assign this to me.

ThankYou:)

**Comment by sakshamgurbhele** [comment]
Hey @purohitmansi , let me know if you are interest in taking this issue.
