### ISSUE TITLE
Enhancement: Add a Background image in the Feedback section

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#134]
![bigb3](https://user-images.githubusercontent.com/83035995/156416088-a4d17100-a523-440f-bb3d-4c6f6c0b59d9.jpg)

**Comment by The-Shivam-garg** [comment]
Thanks for showing the interest in this issue, I have assigned this issue to @saketsagarsingh

**Comment by HarshKumarChoudary** [comment]
I'm GSSOC 22 contributor. If this issue is still available, please assign it to me. Also please add GSSOC22 label for that. Thanks

**Comment by the-centinal** [comment]
please assign this to me under GSSOC 22

**Comment by Apexshya** [comment]
I am GSSOC 22 contributor. Please assign me this project.

**Comment by The-Shivam-garg** [comment]
hey @rutika1823 you can start working on this issue. Thanks to other for showing their interest in this issue .I would recommend you to explore the website and come with other creative ideas for modification

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , I am a GSSOC'22 contributor . Can you please assign this issue to me . I have solved the issue and send the PR . Can you please review and merge it .

**Comment by Rishita489** [comment]
Hey @sakshamgurbhele , you can review and merge my new PR #296 .
