### ISSUE TITLE
Enhancement: Resolve the Spacing & alignment issue 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#135]
![bigb4](https://user-images.githubusercontent.com/83035995/156416348-d2a8eb00-6ba7-4245-b115-9b5798abda15.jpg)

**Comment by the-centinal** [comment]
please assign this task to me under GSSOC2022

**Comment by the-centinal** [comment]
sir exactly what i have to do with the border of image , should i make it cover all the image or remove it??

**Comment by The-Shivam-garg** [comment]
> sir exactly what i have to do with the border of image , should i make it cover all the image or remove it??

cover all the image

**Comment by Mohit-1909** [comment]
Hey is this issue open I would like to work on this.

**Comment by the-centinal** [comment]
sir please check my pr for this issue

**Comment by The-Shivam-garg** [comment]
> sir please check my pr for this issue

your pr has conflicts please resolve them

**Comment by the-centinal** [comment]
conflicts are resolved sir
