### ISSUE TITLE
Enhancement: Make the parameter bar more attractive.

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#136]
![bigb5](https://user-images.githubusercontent.com/83035995/156416570-4bb63da1-ade2-4931-ae83-f3295d5ee0de.jpg)

**Comment by BabyElias** [comment]
Like what colors, if you have any idea in mind? Will surely try working on it once clear with the intended color palette.

**Comment by The-Shivam-garg** [comment]
hey @BabyElias , I'm not sure about the color yet .But as i have one recommendation for this ,for the time you can go with that if you find that suitable .
![bigb6](https://user-images.githubusercontent.com/83035995/156419575-1fbcce56-3809-415d-9cde-09fab72f013c.jpg)

**Comment by BabyElias** [comment]
Ok.Thanks.

**Comment by Cypher1002** [comment]
hey , @The-Shivam-garg  very nice project 
could make some changes in the buttons like adding color gradients and fix the border radius to make it more enhanced 
could add a hover effect also
could you assign me the project under gssoc'22

**Comment by The-Shivam-garg** [comment]
great ! @Cypher1002 you can work on this issue

**Comment by Cypher1002** [comment]
Thanks for assigning it to me will give my best

**Comment by sakshamgurbhele** [comment]
@Cypher1002 what is your update on this issue?

**Comment by Cypher1002** [comment]
@sakshamgurbhele i had given a pull request for the changes i made

**Comment by Diksha4111** [comment]
Can I get the opportunity to work on this issue?
I would be really happy to contribute in this issue :)
