### ISSUE TITLE
Footer is not same in all of the pages 

### ISSUE THREAD

**Issue by the-centinal** [The-Shivam-garg/BigB-E-learn-Websit-e#137]
Footer is not same in all the pages . which makes bad impression., so make same  footer for all the pages

**Comment by the-centinal** [comment]
@admin please assign this issue to me under GSSOC22

**Comment by the-centinal** [comment]
sir please check the pr

**Comment by sakshamgurbhele** [comment]
@the-centinal can you please link you PR with the issue,

**Comment by the-centinal** [comment]
[`https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/pull/162/`]

**Comment by sakshamgurbhele** [comment]
https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/pull/162/
