### ISSUE TITLE
Feature : Add a Interactive Chat Bot 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#14]
Description
Create an animated video about the website explaining its features and add it to the home page of the website.

👀 Have you spent some time to check if this issue has been raised before?

- [x]  I checked and didn't find similar issue

🏢 Have you read the Code of Conduct?

- [x]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/5332d5a97ff58a00a86839db46c37c73e2b15842/CODE_OF_CONDUCT.md)

**Comment by ronitblenz** [comment]
I have worked with Twilio in 3 projects for hackathons, so I can do this for the home page of the website.
