### ISSUE TITLE
The contents under why education are not centered properly.

### ISSUE THREAD

**Issue by rohinish404** [The-Shivam-garg/BigB-E-learn-Websit-e#142]
-Left and right spacing are not equal so it is giving bad impression. 
**EXPECTED BEHABIOUR**
-It should be centered properly.

<img width="1440" alt="Screenshot 2022-03-03 at 10 11 43 AM" src="https://user-images.githubusercontent.com/92542124/156497601-f558a6b7-fc2f-4b29-a7f5-d346431db7c8.png">
<img width="1440" alt="Screenshot 2022-03-03 at 10 13 19 AM" src="https://user-images.githubusercontent.com/92542124/156497683-2aa7b669-e1c2-4f13-9302-8d2798b02025.png">

**Comment by The-Shivam-garg** [comment]
Thanks for recommendation @rohinish404 you can start working on this issue.

**Comment by rohinish404** [comment]
i visited the website once again and now the contents are perfectly centered😯
<img width="1440" alt="Screenshot 2022-03-03 at 12 42 30 PM" src="https://user-images.githubusercontent.com/92542124/156515038-9e26e15e-5f84-4b7d-af24-eafb383b4ce9.png">
