### ISSUE TITLE
Inconsistency in blob radius

### ISSUE THREAD

**Issue by AmanDeep9925** [The-Shivam-garg/BigB-E-learn-Websit-e#146]
As the home page loaded after opening the website the blob note that shows for the first time, it have inconsistency in the border radius. It doesn't feel perfect regarding UI and overall experience of the application.
![image](https://user-images.githubusercontent.com/26117610/156545130-97c132cc-13aa-4702-9af3-b97690ce8828.png)
Please have a look at it.

I would like to fix it.
Please assign this to me 🚀

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest in this issue , I'm assigning this issue to @AmanDeep9925 .

**Comment by AmanDeep9925** [comment]
I will update it as soon as possible

**Comment by AmanDeep9925** [comment]
@The-Shivam-garg as I have taken up the code for my local setup. I have encountered some error in the index.html file as it shows this <<<< HEAD
<<<< HEAD
/...
HTML file content
.../
>>>>>>> 1563d95c834c057383d517c07d78cb5f1a983d37
I doesn't understand this as it shows some conflict in merging with someone PR or I haven't taken up the latest code please check it out once.
As I don't wanna cause some ambiguity for the same file as it shows error in loading the website

**Comment by AmanDeep9925** [comment]
@The-Shivam-garg Please find the attached clip for this message as the main branch shows triplets of the code may be there is a merge conflict. Some one please take it up it looks bad and confusing for 

> @The-Shivam-garg as I have taken up the code for my local setup. I have encountered some error in the index.html file as it shows this <<<< HEAD <<<< HEAD /... HTML file content .../
> 
> > > > > [1563d95](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/commit/1563d95c834c057383d517c07d78cb5f1a983d37)
> > > > > I doesn't understand this as it shows some conflict in merging with someone PR or I haven't taken up the latest code please check it out once.
> > > > > As I don't wanna cause some ambiguity for the same file as it shows error in loading the website

https://user-images.githubusercontent.com/26117610/156613077-d32d1738-8c11-47d9-8bf7-845cebc4edd0.mp4

**Comment by The-Shivam-garg** [comment]
> @The-Shivam-garg Please find the attached clip for this message as the main branch shows triplets of the code may be there is a merge conflict. Some one please take it up it looks bad and confusing for
> 
> > @The-Shivam-garg as I have taken up the code for my local setup. I have encountered some error in the index.html file as it shows this <<<< HEAD <<<< HEAD /... HTML file content .../
> > > > > > [1563d95](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/commit/1563d95c834c057383d517c07d78cb5f1a983d37)
> > > > > > I doesn't understand this as it shows some conflict in merging with someone PR or I haven't taken up the latest code please check it out once.
> > > > > > As I don't wanna cause some ambiguity for the same file as it shows error in loading the website
> 
>  bigB.-.Google.Chrome.2022-03-03.22-24-44.mp4

Resolved thanks for informing me
