### ISSUE TITLE
Enhancement: Spelling and wording check

### ISSUE THREAD

**Issue by ranafathi** [The-Shivam-garg/BigB-E-learn-Websit-e#149]
Some paragraphs and buttons have wrong spelling and grammar usage, which affects the users' ability to read and clearly understand content. I would like to help fix this issue.

![Uploading Untitled.png…]()

**Comment by Stuti-0310** [comment]
Assign me this issue for gssoc'22

**Comment by The-Shivam-garg** [comment]
Thanks for showing interest in this issue but for now I'm assigning this issue to @ranafathi . I would recommend other contributors to explore the website and issue mentioned in issue section .
