### ISSUE TITLE
Inconsistent Feedback Look

### ISSUE THREAD

**Issue by ranafathi** [The-Shivam-garg/BigB-E-learn-Websit-e#150]
This is what feedback currently looks like:
![issue2](https://user-images.githubusercontent.com/45921220/156576225-42bf0acd-50cb-4489-8883-fa980f8a207b.png)

Which is not consistent and overall may be off-putting to users, I think something like scrolling cards of the same size could be a better solution.
![issue2-2](https://user-images.githubusercontent.com/45921220/156576891-d4717a71-e690-4490-b96a-d57a2895c076.png)

**Comment by The-Shivam-garg** [comment]
Thanks @ranafathi for your recommendation , this issue is already mentioned before ,and assigned too. HOPE you will find some more interesting issue to work on .Best wishes for your future contribution. :)

**Comment by sakshamgurbhele** [comment]
@ranafathi you can open more issues if you feel, thank you✨
