### ISSUE TITLE
Feature  : Add a Interactive bot 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#153]

**Comment by Mohit-1909** [comment]
@The-Shivam-garg I would like to work on this, please assign this to me.

**Comment by HarshKumarChoudary** [comment]
I'm GSSOC 22 contributor. If this issue is still available, please assign it to me. Also please add GSSOC22 label for that. Thanks

**Comment by The-Shivam-garg** [comment]
Sorry @Mohit-1909 already you have been assigned with 2 issue that's why i cant assign you one more .hey @HarshKumarChoudary you can work on this issue.

**Comment by sakshamgurbhele** [comment]
@HarshKumarChoudary Are you working on this issue??

**Comment by HarshKumarChoudary** [comment]
I got busy with my exams, so please give me some more days.

**Comment by gurjeetsinghvirdee** [comment]
Assign me 
I will do in just 30mins

**Comment by Adhetya** [comment]
@The-Shivam-garg, I would like to work on this issue. Please assign it to me

**Comment by The-Shivam-garg** [comment]
Hey @Adhetya you can work on this issue
