### ISSUE TITLE
Feature: Creation of Registration Page

### ISSUE THREAD

**Issue by Kumar-laxmi** [The-Shivam-garg/BigB-E-learn-Websit-e#158]
A link of registration is provided in Footer section.

So, I can create a new registration page and link to it.

**Comment by The-Shivam-garg** [comment]
its already their , Signup and sign in feature you can link that in the footer

**Comment by Kumar-laxmi** [comment]
Nope the sign in and sign up are different to registration
![image](https://user-images.githubusercontent.com/76027425/156863558-7c5719ed-6530-4b2e-9228-d0502587df26.png)
Sign In and Sign Up are only got authorised personels what about students

**Comment by Kumar-laxmi** [comment]
The above image is just a sample

**Comment by The-Shivam-garg** [comment]
no need for this as the site is for the learners not just only for the students.

**Comment by Kumar-laxmi** [comment]
Ok
