### ISSUE TITLE
Hover Effect on cards in Home and Blogs Page

### ISSUE THREAD

**Issue by Anirban-1490** [The-Shivam-garg/BigB-E-learn-Websit-e#159]
I want to work on this under GSSOC22

also don't know if there is a issue on this currently opened

On this cards 
![Opera Snapshot_2022-03-04_150339_the-shivam-garg github io](https://user-images.githubusercontent.com/82874704/156738215-292e5d39-c5f8-4d13-a552-69095a4d32ad.png)
![Opera Snapshot_2022-03-04_150402_the-shivam-garg github io](https://user-images.githubusercontent.com/82874704/156738233-30ee2e51-787b-4b0e-98ac-d626d3d96403.png)

**Comment by The-Shivam-garg** [comment]
sure you can work on this issue @Anirban-1490

**Comment by Anirban-1490** [comment]
> sure you can work on this issue @Anirban-1490

thank you
