### ISSUE TITLE
Tweaks Needed in For Latest updates section

### ISSUE THREAD

**Issue by AmanDeep9925** [The-Shivam-garg/BigB-E-learn-Websit-e#161]
@The-Shivam-garg, 
Hi, I was going through the website and this catches my sight as there is a lot of changes required for this section 
Here you can find the attached screenshot
![image](https://user-images.githubusercontent.com/26117610/156796001-df669501-0369-4701-bd63-a29015686e06.png)

FIX: Suggested
[]: Input has a bottom border which doesn't seems right to have there
[]: Submit button has to be revamped and needed some tweaks

I would like to take up these changes.

**Comment by The-Shivam-garg** [comment]
thank you for your recommendation but someone is already working on this issue

**Comment by AmanDeep9925** [comment]
Thanks for update
