### ISSUE TITLE
Feature: Change Sign Up buttons to Sign In

### ISSUE THREAD

**Issue by Kumar-laxmi** [The-Shivam-garg/BigB-E-learn-Websit-e#165]
### Description

**This is under GSSoC'22**

On Home Page we can wee that at top-right we have sign up button.
On clicking it, it leads us to Sign In page.
On most websites what we see first is Sign In button.

### Screenshots

![image](https://user-images.githubusercontent.com/76027425/156878546-9206501a-e465-4cef-8f5c-6661387b3cbf.png)
![image](https://user-images.githubusercontent.com/76027425/156878555-22df961d-809e-49ef-8261-c01474d7d29e.png)

**Comment by Kumar-laxmi** [comment]
So you can see that Sign Up button leads to Sign In page

**Comment by gullapalli9482** [comment]
I would like to work on this, can someone assign it to me, if it's unassigned

**Comment by The-Shivam-garg** [comment]
You can work on this issue @Kumar-laxmi

**Comment by rishav-karanjit** [comment]
@The-Shivam-garg Although you had said to work on this issue first, can I work on it? I have a project to do where I should be solving Github issues. If solving this issue is not important for you, can I work on it?

**Comment by The-Shivam-garg** [comment]
> @The-Shivam-garg Although you had said to work on this issue first, can I work on it? I have a project, of a subject I am studying, where I should be solving Github issues . If solving this issue is not important for you, can I work on it?

Sorry @rishav-karanjit  It's already assigned , you can explore the website and can come up with your creative ideas

**Comment by rishav-karanjit** [comment]
Sure. Not a issue @The-Shivam-garg
