### ISSUE TITLE
Enhancement : Link the Event in the footer with the event page

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#168]
![image](https://user-images.githubusercontent.com/83035995/156893901-22cccb17-06fd-453a-9ce3-72c29ca25639.png)

**Comment by rishav-karanjit** [comment]
Hello @The-Shivam-garg, can I work on this issue?

**Comment by The-Shivam-garg** [comment]
sure you can @rishav-karanjit

**Comment by rishav-karanjit** [comment]
Thank you @The-Shivam-garg

**Comment by rishav-karanjit** [comment]
@The-Shivam-garg where should I link the events? Like at which URL?

**Comment by rishav-karanjit** [comment]
Got it maybe. Is it [this](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/main/Events/events.html)?

**Comment by rishav-karanjit** [comment]
@The-Shivam-garg I have opened a PR for this issue. Thank you!!!

**Comment by rishav-karanjit** [comment]
Also, there is another issue some footer text appear to have black font color which makes them invisible as background is also black. Can I open this issue?
