### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#17]

**Comment by rohit-raj25** [comment]
I want to work on this issue under JWOC

**Comment by Shresa** [comment]
I want to work on this issue under JWOC

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by rohit-raj25** [comment]
1. From which pages I should start first.?
2. We have to make the site responsive on three devices desktop, tab, and phone, right?

**Comment by The-Shivam-garg** [comment]
1. you can start with the home page.
2.yeah! rohit we have to make the website responsive for all three.

**Comment by sakshamgurbhele** [comment]
Thank You for contributing, 🚀😇
