### ISSUE TITLE
Improvements in footer and hover effect of an element

### ISSUE THREAD

**Issue by Nitya-S27** [The-Shivam-garg/BigB-E-learn-Websit-e#170]
### Description

- The footer has two columns for information. The title of one of them needs to be changed.
- Also the font color of the links is black which is overlapping with the background color of the footer.
- The icons are also not aligned properly.
- The hover effect of last child in the what we offer section is also overflowing and can be improved!

### Screenshots

**Glitch in footer**
![Screenshot (373)](https://user-images.githubusercontent.com/81871441/156908618-d4652b1a-79a9-4aa8-b795-2f54fdbe2560.png)

**Problem with the hover effect**
![Screenshot (374)](https://user-images.githubusercontent.com/81871441/156908621-4d7e97c6-b01e-4e8d-ab5a-6e732396df50.png)

**Comment by Nitya-S27** [comment]
@The-Shivam-garg can you please assign this issue to me?
Thanks and Regards.

**Comment by The-Shivam-garg** [comment]
yeah @Nitya-S27 you can work on your last issue which is :
 The hover effect of last child in the what we offer section is also overflowing and can be improved!

as above three issues are already resolved . Thanks for your recommendation .

**Comment by piyush-sri** [comment]
@The-Shivam-garg  could you please assign this issue to me?
I would like to deal with the footer issues !!.
