### ISSUE TITLE
Bug : Student count increasing without validation

### ISSUE THREAD

**Issue by soujo** [The-Shivam-garg/BigB-E-learn-Websit-e#174]
When any user is subscribing to the newsletter, without any validation for the email the students enrolled count is increasing.
I want to fix this issue under JWOC @The-Shivam-garg 

https://user-images.githubusercontent.com/78646418/156983057-3390c4c5-0c30-411c-970d-09837844bec3.mp4

**Comment by The-Shivam-garg** [comment]
sure @soujo you can work on this issue
