### ISSUE TITLE
Change the year in the footer

### ISSUE THREAD

**Issue by Nitya-S27** [The-Shivam-garg/BigB-E-learn-Websit-e#176]
### Description

The footer year still says 2021 and must be changed.
Same issue with the Readme.md file.

### Screenshots

![image](https://user-images.githubusercontent.com/81871441/157036532-40747cda-3827-485c-acbe-9b03b64556fd.png)

**Comment by Shofiya2003** [comment]
Can I resolve this issue?

**Comment by Nitya-S27** [comment]
> Can I resolve this issue?

@Shofiya2003 I have raised the issue and it is to be solved by me once assigned

**Comment by The-Shivam-garg** [comment]
@Nitya-S27 you can work on this issue
