### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#18]

**Comment by ZaidMujahid** [comment]
I want to work on this issue under JWOC

**Comment by Kaggrov** [comment]
I want to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
I'm assigning this issue to both of you , whosoever preloader is best i will merge that. @Kaggrov @ZaidMujahid

**Comment by ZaidMujahid** [comment]
@The-Shivam-garg Mentor, as per the rules you have to assign the issue to the person who commented first, and you can tell that person to make changes if you don't like it

**Comment by The-Shivam-garg** [comment]
Ohk no issuee the one who commented first will start working on it. After
some time i will offically  assign it to that person .

**Comment by ZaidMujahid** [comment]
Okay thank you, btw I commented first

**Comment by ZaidMujahid** [comment]
Please add a JWOC tag to this issue and also while merging

**Comment by The-Shivam-garg** [comment]
Sure dont worry about it
