### ISSUE TITLE
Change JOIN FREE ONLINE COURSES section in index.html

### ISSUE THREAD

**Issue by heyvats21** [The-Shivam-garg/BigB-E-learn-Websit-e#191]
### Description

- Will change CSS of this section. 

I want to work on this issue under  GSSOC'22 .

### Screenshots

![image](https://user-images.githubusercontent.com/81029204/157921490-14e836e3-00f3-4627-b59b-5f5bfd4af113.png)

**Comment by The-Shivam-garg** [comment]
sure @heyvats21

**Comment by sakshamgurbhele** [comment]
This issue is resolved! Kindly look into other issue
