### ISSUE TITLE
[FEATURE] Create Resource page

### ISSUE THREAD

**Issue by Kumar-laxmi** [The-Shivam-garg/BigB-E-learn-Websit-e#193]
### Description

**THIS IS UNDER GSSoC'22**

I can see that there is a link to Resources but no page has been linked for resources
![image](https://user-images.githubusercontent.com/76027425/158092756-c696f484-be5f-407b-88fd-df14564c7474.png)

So I can create one just like the image attached below

### Screenshots

![157244712-5070fa2b-1e9f-4061-a835-423137a144e5](https://user-images.githubusercontent.com/76027425/158092920-487d5737-0735-4287-88cf-78fa04357cb0.png)

This image is just a sample, I will use template of this website but the idea would be same

**Comment by sakshamgurbhele** [comment]
seems cool, @Kumar-laxmi Go Ahead!
