### ISSUE TITLE
Enhancement : make the button styling more consistent.

### ISSUE THREAD

**Issue by SwathiReddy03** [The-Shivam-garg/BigB-E-learn-Websit-e#197]
![image](https://user-images.githubusercontent.com/98385147/158837903-08b710cf-c843-4cec-9253-b446dfacb54d.png)
![image](https://user-images.githubusercontent.com/98385147/158837996-e7358997-63a8-4f0d-8ed4-3bde8c4c7a28.png)

these are not similar to the ones below

![image](https://user-images.githubusercontent.com/98385147/158838246-8dc196cf-f122-4eac-8b66-6e298ec83e93.png)

I would like to work on this 
please assign me this issue 
I am a GSSOC contributor.

**Comment by sakshamgurbhele** [comment]
Hey @SwathiReddy03, Sure Go ahead!
