### ISSUE TITLE
Links Issue

### ISSUE THREAD

**Issue by Atif0604** [The-Shivam-garg/BigB-E-learn-Websit-e#20]
Fix Link issue in courses page ,
Fix all Link in navbar blog page,
Fix Link issue in contact us page ,

**Comment by Atif0604** [comment]
I want to work on this issue under JWOC
@The-Shivam-garg

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
> I want to work on this issue under JWOC @The-Shivam-garg

sure @Atif0604 . you have assigned with this issue
