### ISSUE TITLE
[FEATURE]  Add a button which toggles the view of password(show/hidden)

### ISSUE THREAD

**Issue by Siddhesh777** [The-Shivam-garg/BigB-E-learn-Websit-e#202]
### Description

So many times user wants to know the password he entere is correct or not or user wants to know what password he/she has entered. For the there must be a button which toggles the visibility of password.

I am contributor at gssoc'22.
Please assign this issue to me.

### Screenshots

![1](https://user-images.githubusercontent.com/77476772/159117450-70c9d81d-ef27-4c0f-92af-c45bb25797c6.png)
![2](https://user-images.githubusercontent.com/77476772/159117455-db78c8bb-fc63-4c67-8941-853e9b30e58f.png)

**Comment by sakshamgurbhele** [comment]
@Siddhesh777 Go Ahead! Assigning it to you 🚀
