### ISSUE TITLE
[Enhancement] Fixing the images in the courses page

### ISSUE THREAD

**Issue by ktyayani** [The-Shivam-garg/BigB-E-learn-Websit-e#203]
### Description

I tried looking if someone has already raised this issue but couldn't find any so here it is, the images on the buttons in the courses page are kind of stretched and look weird. I'd like to fix them by switching to new ones/fixing current ones if anyone has the original copies if it's possible to be assigned this as an issue. It will help improve the visual of the website.

### Screenshots

![Screenshot_2022-03-19-16-11-09-46](https://user-images.githubusercontent.com/63457181/159117781-87e121a2-f796-41f8-be83-accc5bad4fac.jpg)

**Comment by sakshamgurbhele** [comment]
@ktyayani Go ahead, Assigning it to you 🚀
