### ISSUE TITLE
[FEATURE] Add round edges to "WHAT WE OFFER" section

### ISSUE THREAD

**Issue by sakshamgurbhele** [The-Shivam-garg/BigB-E-learn-Websit-e#204]
## who doesn't love round edges right??? 
task: make the edges round in the **WHAT WE OFFER** section of the home page!

<img width="1437" alt="Screenshot 2022-03-19 at 5 37 40 PM" src="https://user-images.githubusercontent.com/64558515/159120457-1b347856-6769-4035-976d-e900db18b774.png">

**Comment by The-Arshad-Khan** [comment]
@The-Shivam-garg Sir, Kindly Assign This Issue To Me!

**Comment by the-centinal** [comment]
@admin  please assign this issue to me under GSSOC2022

**Comment by Diksha4111** [comment]
Can I get the opportunity to work on this issue?
