### ISSUE TITLE
make the UI cleaner

### ISSUE THREAD

**Issue by sakshamgurbhele** [The-Shivam-garg/BigB-E-learn-Websit-e#205]
## This doesn't look good right? 
<img width="1000" alt="Screenshot 2022-03-19 at 5 41 37 PM" src="https://user-images.githubusercontent.com/64558515/159120616-69bca337-d2db-4b3d-8c17-d8ffc6c6420b.png">

### Task: Upgrade the UI, full liberty given to contributor, customise as you want. 
- the input box, the button, the hint text. go for all. 

location: Home Page

**Comment by Sandhya312** [comment]
Hey, @sakshamgurbhele  I am a GSSOC'22 contributor.
I want to work on this project. Please assign it to me.

**Comment by sakshamgurbhele** [comment]
@Sandhya312 Go Ahead! Assigning it to you 🚀

**Comment by Sandhya312** [comment]
Hey @sakshamgurbhele  Pls check the pull request #212

**Comment by sakshamgurbhele** [comment]
hey @Diksha4111, this is done, you can look in for other issues.

**Comment by Diksha4111** [comment]
Ok thank you :)
