### ISSUE TITLE
Confirm Password field while signing up the page.

### ISSUE THREAD

**Issue by Siddhesh777** [The-Shivam-garg/BigB-E-learn-Websit-e#210]
### Description

It may happen that while registering the user may type a wrong key while entering the password.
So there must be a "Confirm Password" field. If both the password match then only the user can register.

I am contributor at gssoc'22.
Please assign this issue to me. 

### Screenshots

![1](https://user-images.githubusercontent.com/77476772/159228675-b0a93bb2-11b7-4a8b-94e9-419374a634ca.png)

**Comment by Diksha4111** [comment]
Can I get the opportunity to work on this issue?

**Comment by rutika1823** [comment]
Please assign me this issue for gssoc'22. I would like to work on same.

**Comment by The-Shivam-garg** [comment]
hey @Siddhesh777 you can work on this issue
