### ISSUE TITLE
[DOCS] Make the format more align and clear

### ISSUE THREAD

**Issue by sakshamgurbhele** [The-Shivam-garg/BigB-E-learn-Websit-e#218]
### Description

as you can see the headings are not properly aligned, the text is inconsistent
The Hyperlinks are also not in the aligned format. 

<img width="985" alt="Screenshot 2022-03-25 at 8 53 22 PM" src="https://user-images.githubusercontent.com/64558515/160150178-171afd65-9db8-4490-8e85-8e1db4c5f288.png">
this para can also me formatted well.
<img width="936" alt="Screenshot 2022-03-25 at 8 54 07 PM" src="https://user-images.githubusercontent.com/64558515/160150297-b08b60ae-8121-4530-b44b-1a2fe497899a.png">

**Comment by Mvaishu10** [comment]
Heyy ,I'm intrested can I work on it?

**Comment by sakshamgurbhele** [comment]
Sure, Go Ahead @Mvaishu10. Assigning it to you 🚀

**Comment by Pranai2518** [comment]
If he is unable to do. I would like to work on this as a gssoc participant.

**Comment by The-Shivam-garg** [comment]
hey @Pranai2518 you can start working on this issue
