### ISSUE TITLE
Improve Footer

### ISSUE THREAD

**Issue by Areebah03** [The-Shivam-garg/BigB-E-learn-Websit-e#221]
### Description

I want to improve the footer by modifying design and hover effect. Please assign it to me :)

### Screenshots

![Screenshot 2022-03-26 111647](https://user-images.githubusercontent.com/85051124/160226708-6f9da2a9-4a10-4410-bb8a-3ccce355570e.png)

**Comment by The-Shivam-garg** [comment]
yeah! @Areebah03 you can start working on this issue
