### ISSUE TITLE
Want to improve "Why Education " section by adding hovering effect that changes background color of cards

### ISSUE THREAD

**Issue by Himanshi236** [The-Shivam-garg/BigB-E-learn-Websit-e#222]
### Description

Hey I want to add hovering to the the cards in the "Why Education" section, it will look more attractive and catchy.
Please assign me this issue under GSSOC'22.

**Comment by The-Shivam-garg** [comment]
@Himanshi236 you can start working on this issue

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , I am a GSSOC'22 contributor . Can you assign this issue to me . I have send the PR solving this issue . You can review and merge it .
