### ISSUE TITLE
Same text color and hover color.

### ISSUE THREAD

**Issue by Ranjana550** [The-Shivam-garg/BigB-E-learn-Websit-e#226]
### Description

Here, after hovering to text under have question part, because of the same hover color and text color, the text is unrecognizable.

 

### Screenshots

Here, 
![image](https://user-images.githubusercontent.com/71266173/161232163-f5b1831e-c37f-4e89-bdfe-46d420da0218.png)

this is how
![Screenshot (493)_LI](https://user-images.githubusercontent.com/71266173/161232515-41bafce4-e2c1-4e3f-963d-5c60c6a8a253.jpg)

**Comment by Ranjana550** [comment]
> ### Description
> Here, after hovering to text under have question part, because of the same hover color and text color, the text is unrecognizable.
> 
> ### Screenshots
> Here, ![image](https://user-images.githubusercontent.com/71266173/161232163-f5b1831e-c37f-4e89-bdfe-46d420da0218.png)
> 
> this is how ![Screenshot (493)_LI](https://user-images.githubusercontent.com/71266173/161232515-41bafce4-e2c1-4e3f-963d-5c60c6a8a253.jpg)

I would like to work on this issue. Please assign it to me.

**Comment by The-Shivam-garg** [comment]
yeah sure ! @Ranjana550 you can work on this issue

**Comment by Ranjana550** [comment]
> yeah sure ! @Ranjana550 you can work on this issue
Thank you! 👍🏻

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , I am a GSSOC'22 contributor .  Can you please assign this issue to me . I have send the PR . You can review and merge it .

**Comment by Ranjana550** [comment]
> Hey @The-Shivam-garg , I am a GSSOC'22 contributor . Can you please assign this issue to me . I have send the PR . You can review and merge it .

Hey...I am also done with the implementation. 
It's good you did it, but it's not a correct way to make a PR if someone else is already assigned to that issue. Hope you understand it.  )

**Comment by Ranjana550** [comment]
> yeah sure ! @Ranjana550 you can work on this issue

@The-Shivam-garg it's done.  I have made a PR as well, please check it out.

**Comment by Rishita489** [comment]
You can review my PR once . I have made changes to  the hover color such that it aligns with the theme of the website .

**Comment by The-Shivam-garg** [comment]
hey @Ranjana550 can you please any other impressive effect for this one , like it seems a little odd

**Comment by Ranjana550** [comment]
> hey @Ranjana550 can you please any other impressive effect for this one , like it seems a little odd

Yes, sure. I will.  👍🏻 
But, I think @Rishita489's PR is also merged along with mine that's why it's looking a little odd with two different colors(blue and white) after hovering on text.

**Comment by Ranjana550** [comment]
> > hey @Ranjana550 can you please any other impressive effect for this one , like it seems a little odd
> 
> Yes, sure. I will. 👍🏻 Actually, I did changes according to how it is done on other pages. ![Screenshot (496)_LI](https://user-images.githubusercontent.com/71266173/161442811-247e4442-b26c-4a42-847a-f7f01753066d.jpg) Like here, how it is done for other texts and links.
> 
> But, I think @Rishita489's PR is also merged along with mine that's why it's looking a little odd with two different colors(blue and white) after hovering on text.

Working on it. It would be done by today evening or max by tomorrow morning.

**Comment by Ranjana550** [comment]
> hey @Ranjana550 can you please any other impressive effect for this one, like it seems a little odd

Heyy, @The-Shivam-garg 
It's done.  Changed the hover background color to how it is being done for other hyperlinks to keep similarity.
![Screenshot (496)_LI](https://user-images.githubusercontent.com/71266173/161731488-f7a182b2-f1ff-43b8-bdc1-e7e9aa17d7e9.jpg)
![Screenshot (495)_LI](https://user-images.githubusercontent.com/71266173/161731510-bff5f108-3649-42e3-9ca6-6739584a131c.jpg)

I have made a PR as well please check it out.
If there are any changes that need to be done, please do let me know. I will rectify that.
Thank you! : )
