### ISSUE TITLE
[FEATURE] UI makeover

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#228]
### Description

Create more attractive glow effect ,It wont seems good

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161395720-20b7f5ab-356e-44e2-9657-57ebab06a3da.png)

**Comment by Pranai2518** [comment]
I would like to work on this as a gssoc participant.

**Comment by GeekAmita** [comment]
Please assign me this issue. I'm a contributor at GSSoC'22.

**Comment by The-Shivam-garg** [comment]
Hey @Pranai2518 , you can start working on this issue.

**Comment by Pranai2518** [comment]
Hey @The-Shivam-garg.  The text effect was changed like this by you. what should I do now.
![1](https://user-images.githubusercontent.com/75829770/161597274-7924e384-1ea4-4036-b746-7653e6048d09.png)

**Comment by The-Shivam-garg** [comment]
hey @Pranai2518 , yeah i have changed that as it is not appropriate , if you can have any other idea to make it look more attractive ,please do create issue about same i will assign you

**Comment by Pranai2518** [comment]
Hey @The-Shivam-garg as of now it looks fine. If I get an idea on making it more creative. I'll make an issue then.
