### ISSUE TITLE
[Enhancement] Make it more appropriate

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#230]
### Description

It should be like:

# HEADING 
### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161395654-0e6614f7-ac6c-4a44-90ad-440803390bba.png)

**Comment by Siddhesh777** [comment]
@The-Shivam-garg 
I am interested .
Please assign this issue to me.

**Comment by GeekAmita** [comment]
Please assign me this issue. I'm a contributor at GSSoC'22.

**Comment by The-Shivam-garg** [comment]
hey @Siddhesh777 you can start working on this issue
