### ISSUE TITLE
Elements are not properly aligned in BLOG section

### ISSUE THREAD

**Issue by Anjuli08** [The-Shivam-garg/BigB-E-learn-Websit-e#233]
### Description

sign in button in the blog section is not properly aligned as it is getting cut 

### Screenshots

![Screenshot (38)_LI](https://user-images.githubusercontent.com/90701800/161417452-1bfd15a0-531c-466a-968c-6a493e03ed81.jpg)

**Comment by Anjuli08** [comment]
kindly assign me this, if required

**Comment by Anjuli08** [comment]
kindly assign me this issue

**Comment by The-Shivam-garg** [comment]
@Anjuli08 you can work on this issue
