### ISSUE TITLE
[FEATURE]  Wan to Fix navbar, its reponsiveness, its UI and many more things that are glitched somehow

### ISSUE THREAD

**Issue by Abh1shekSingh** [The-Shivam-garg/BigB-E-learn-Websit-e#238]
### Description

I want to fix overall website according to UI UX theory

**Comment by Abh1shekSingh** [comment]
Please Assign this issue to me. I will fix every thing. Supafast

**Comment by The-Shivam-garg** [comment]
Thanks @Abh1shekSingh you can start working on this issue

**Comment by Abh1shekSingh** [comment]
Code is so messy. Its really really hard to understand. Everything is mixed up. Really poor structure.
