### ISSUE TITLE
When we click on the Home button in Navbar while we are on the Home Page an error 404 page comes 

### ISSUE THREAD

**Issue by aadrikasingh18** [The-Shivam-garg/BigB-E-learn-Websit-e#24]
I want to resolve this issue such that, that error does not come and we stay on the same page.

Also, I will make all the Navbar items in the same Case (ie Upper Case)
![Screenshot (15462)](https://user-images.githubusercontent.com/91376920/152032924-724c4ebe-f64a-4171-9677-b6b7ade1cf7c.png)

**Comment by aadrikasingh18** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
Thank you all of you for showing your interest in this issue . But for now being I'm assigning this issue to @aadrikasingh18      because of earlier comment. Other's can explore the website .
Best wishes for your future contribution in the Open-source.😊

**Comment by The-Shivam-garg** [comment]
Thank you  @aadrikasingh18 , for resolving out the issue. i have merged your code into the repository. 
Now I'm closing the issue.
