### ISSUE TITLE
[FEATURE] Adding link to the Courses 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#242]
### Description

Hey Contributor!
we want you to make each of these Block connect with the course page and its required course.

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161472669-d2aad613-1565-41c6-ba6c-04bca8e7a59d.png)

**Comment by Siddhesh777** [comment]
hey @The-Shivam-garg 
Please assign this to me

**Comment by The-Shivam-garg** [comment]
hey @Siddhesh777 you can start working on this issue

**Comment by Siddhesh777** [comment]
hey @The-Shivam-garg 
Where are the pages of these courses which should be linked.

**Comment by The-Shivam-garg** [comment]
course page
