### ISSUE TITLE
[FEATURE] Add the original blogs and make them directing

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#244]
### Description

Add the original blogs and make them directing .i.e. we want you to change the images and content according to the blog title you choose and make it redirecting to the actual blog 

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161473525-ca36cec9-2d6d-4322-a431-597d0f7ac74f.png)

**Comment by gurjeetsinghvirdee** [comment]
I want to work assign me

**Comment by The-Shivam-garg** [comment]
sure @gurjeetsinghvirdee you can start working on this issue
