### ISSUE TITLE
[FEATURE] make Footer links Redirecting with their actual page in the website

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#245]
### Description

Make Footer links Redirecting with their actual page in the website.
The socials links you can get from the Readme File 

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161473808-c3f247a2-bcf4-4e8c-9c58-2fe8757d2980.png)

**Comment by Pranai2518** [comment]
I would like to work on this issue under gssoc. please assign me.

**Comment by The-Shivam-garg** [comment]
hey @Pranai2518 i have assigned you the issue

**Comment by RohanHarichandan** [comment]
Hey is there any way I can contribute
