### ISSUE TITLE
Scroll to top button in feature page.

### ISSUE THREAD

**Issue by Siddhesh777** [The-Shivam-garg/BigB-E-learn-Websit-e#247]
### Description

I would like to make a button which will take user to the top of the feature page in smooth manner.

I am contributor at GSSOC'22.
Please assign this issue to me.

### Screenshots

![1](https://user-images.githubusercontent.com/77476772/161481321-955d098d-18c6-4879-88fc-2aad09c051cf.png)

**Comment by The-Shivam-garg** [comment]
hey @Siddhesh777 you can start working on this issue
