### ISSUE TITLE
Redesign footer in contact us page

### ISSUE THREAD

**Issue by Adhetya** [The-Shivam-garg/BigB-E-learn-Websit-e#253]
### Description

The footer is too big and UI is not looking good in the contact us page. This can be fixed by changing styling, positioning text elements horizontally and give more spacing. I am a GSSOC 22 contributor. Please assign this issue to me.

### Screenshots

<img width="1440" alt="Screenshot 2022-04-05 at 11 02 01 AM" src="https://user-images.githubusercontent.com/20537150/161685884-d0646b71-20a8-4cc0-a5fa-e949c3ff70da.png">

**Comment by The-Shivam-garg** [comment]
Hey @Adhetya you can start working on this issue

**Comment by The-Shivam-garg** [comment]
> hey buddy.. @The-Shivam-garg assign me the task....i can easily make it look good... and can also make necessary changes... would love help you out...

hey @hs-07 , the issue is already assigned i will suggest you to explore the project and issue section to get the best first issue for you

**Comment by hs-07** [comment]
@The-Shivam-garg but as you mentioned that the work hasn't been started  over it
