### ISSUE TITLE
Fix explore section ,some of links are not working properly 

### ISSUE THREAD

**Issue by codingkush** [The-Shivam-garg/BigB-E-learn-Websit-e#258]
### Description

I want to fix explore section because some of the part's  links ( home ,blog , contact, about) are not working properly.

### Screenshots

![Screenshot_20220405-181549~3](https://user-images.githubusercontent.com/78756312/161758330-3001b101-9f1f-468f-8a8f-115d3e9c1aaf.png)

![Screenshot_20220405-181610](https://user-images.githubusercontent.com/78756312/161757999-42e4ba19-fd5b-4643-86e6-484324bd2503.png)

**Comment by codingkush** [comment]
I'm GSsoc 22 contributer and i want to work on this issue under GSsoc 22....plz assign it to me

**Comment by The-Shivam-garg** [comment]
hey @codingkush you can start working on this issue

**Comment by codingkush** [comment]
Hello ....i sent pr for both

**Comment by codingkush** [comment]
Issues so should I send again pr for this

**Comment by codingkush** [comment]
I created 2 issue ...but I sent 1 pr for both...so can I send again pr
