### ISSUE TITLE
Dark mode button position is not good 

### ISSUE THREAD

**Issue by codingkush** [The-Shivam-garg/BigB-E-learn-Websit-e#259]
### Description

Dark mode button is showing on the bottom that doesn't look good.

![Screenshot_20220405-182835~2](https://user-images.githubusercontent.com/78756312/161759132-0821fedb-5650-47c5-bb58-37f208d04980.png)

**Comment by codingkush** [comment]
I want to work on this issue under GSsoc 22....plz assign it to me

**Comment by The-Shivam-garg** [comment]
Hey @codingkush you can start working on this issue

**Comment by yogesh-9999** [comment]
Hey @The-Shivam-garg please assign me this issue.

**Comment by codingkush** [comment]
@yogesh-9999 i have already fixed this issue this but i forgot to close this issue.....

PR of this issue : #277 

![Screenshot_20221002-220716~2](https://user-images.githubusercontent.com/78756312/193465615-029d9be5-72f0-4777-b695-0f41c5c4f226.png)
