### ISSUE TITLE
[FEATURE] Want to change UI of Navbar

### ISSUE THREAD

**Issue by Siddhesh777** [The-Shivam-garg/BigB-E-learn-Websit-e#260]
### Description

I will add some padding in every button of Navbar.
Along with that I will add some nice looking background color to every button and also want to give border radius to it.

I am contributor at GSSOC'22.
Please assign this issue to me.

**Comment by Siddhesh777** [comment]
hey @The-Shivam-garg 
Please assign this to me.

**Comment by The-Shivam-garg** [comment]
Hey @Siddhesh777 before creating new issue please search for  it if the similar one exist or not , don't create the same issue .Please have a look to the issue once you will get this issue already
