### ISSUE TITLE
[FEATURE] Custom Scroll bar

### ISSUE THREAD

**Issue by Pranai2518** [The-Shivam-garg/BigB-E-learn-Websit-e#261]
### Description

The scroll bar which was there right now was the basic one. I would like to customise the scroll bar according to the webpage theme. 

Please assign me under gssoc.

**Comment by The-Shivam-garg** [comment]
Sure @Pranai2518 you can start working on this , But before assigning this i want your confirmation about the previous you have taken , is their any pending issue you are working on ?

**Comment by Pranai2518** [comment]
Hey, @The-Shivam-garg I have no pending issue.
