### ISSUE TITLE
[FEATURE] Change the TESTIMONIAL TEXT to something meaning full, and try to maintain a similar flow for format and content size.

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#263]
### Description

Change the TESTIMONIAL TEXT to something meaning full, and try to maintain a similar flow for format and content size.

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161881961-cfaf2325-350b-49a1-9cf4-89bfc6e143f6.png)

**Comment by Pranai2518** [comment]
I would like to work on this. please assign me.
