### ISSUE TITLE
[FEATURE] Fixing the Course images in the course section 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#264]
### Description

 the images on the buttons in the courses page are kind of stretched and look weird. fix them by switching to new ones/fixing current ones . It will help improve the visual of the website.

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161882279-54161344-b874-45d6-b088-3610c138746a.png)

**Comment by Pranai2518** [comment]
Hey, @The-Shivam-garg I can take this up. Please assign me.

**Comment by The-Shivam-garg** [comment]
hey @Pranai2518 you can start working on this issue

**Comment by Pranai2518** [comment]
Hey @The-Shivam-garg I had changed the images like this
![image](https://user-images.githubusercontent.com/75829770/162132844-8646c49c-85a1-4bcc-a999-3b8d4faa1c24.png)

The same was there down below. Should I remove it or change it as well like the above one
![image](https://user-images.githubusercontent.com/75829770/162132585-ad86f3d0-812c-4ecb-a9d5-27cb1fff31c8.png)

**Comment by Pranai2518** [comment]
Hey, @The-Shivam-garg any response? I'm good to make a PR.
