### ISSUE TITLE
[FEATURE] Create the new page for the Saved option.

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#265]
### Description

Create the new page for the Saved option.the idea behind it is simple that we want user to save their material ,so they can easily get back to it

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161882928-c2a35e6d-7221-4827-b170-d5767d2f68dd.png)

**Comment by aytida0606** [comment]
I want to work on this issue.

**Comment by The-Shivam-garg** [comment]
Hey @aytida0606  you can start working on this issue !

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?
