### ISSUE TITLE
[FEATURE] Design a UI for Counselling Page

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#267]
### Description

try to make something eye catching 

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161883692-47058d1d-b617-4fa8-9956-98ee013f6589.png)

**Comment by Adhetya** [comment]
Can I work on this issue?

**Comment by The-Shivam-garg** [comment]
Hey @Adhetya  you can start working on this issue !
