### ISSUE TITLE
[FEATURE] better UI page of "Team".

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#268]
### Description

the current one , won't seems that good try to make something better

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161884004-b3b4aa55-66d3-4278-a4b3-ca8df4deab37.png)

**Comment by SwathiReddy03** [comment]
Hey 
I am a GSSOC contributor.
I would like to work on this
please assign me this issue

**Comment by aytida0606** [comment]
I want to work on this issue.

**Comment by The-Shivam-garg** [comment]
Hey @SwathiReddy03  you can start working on this issue !

**Comment by Adhetya** [comment]
Can I work on this issue if its still open?

**Comment by Adhetya** [comment]
@The-Shivam-garg, I would like to work on this issue. Please assign it to me
