### ISSUE TITLE
[FEATURE] Add more relevant courses in the Course page 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#269]
### Description

You can add any course in the course section it's open to all domain ,till yet it only consist of curriculum based courses , but we would like , if you can add courses related to :
>Personal Growth
>Marketing
>Startup 
>Spirituality 
and so on

**Comment by gurjeetsinghvirdee** [comment]
assign me

**Comment by The-Shivam-garg** [comment]
hey @gurjeetsinghvirdee you can start working on this issue

**Comment by Vanshika7902** [comment]
I would like to work on this issue .Kindly assign it to me.

**Comment by The-Shivam-garg** [comment]
Hey @Vanshika7902  you can start working on this issue !

**Comment by kusumita29** [comment]
Can I work on this issue? @The-Shivam-garg

**Comment by kusumita29** [comment]
Can you assign me this issue? @The-Shivam-garg
