### ISSUE TITLE
[FEATURE] Create UI for a Community Club page 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#270]
### Description

we are expecting in this issue you to develop a new page for the community perspective .Down below is the screenshot of the example you can consider 

### Screenshots

![community page](https://user-images.githubusercontent.com/83035995/161885475-a7c05744-3d8f-4b2c-ba82-349694564665.png)

**Comment by Adhetya** [comment]
Can I work on this?

**Comment by The-Shivam-garg** [comment]
hey @Adhetya you can work on this issue
