### ISSUE TITLE
Fix the course page 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#271]
### Description

Fix the Course page 

### Screenshots

![image](https://user-images.githubusercontent.com/83035995/161885682-443bb667-d7a4-4057-8990-854cf25d9a51.png)
![image](https://user-images.githubusercontent.com/83035995/161885700-556dca69-4aca-4bd8-9256-79acb30e885d.png)
![image](https://user-images.githubusercontent.com/83035995/161885726-63c65161-0415-4ce6-a1cd-0562da08bcee.png)

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , I am a GSSOC'22 Contributor . Can you please assign this issue to me .

**Comment by The-Shivam-garg** [comment]
hey @Rishita489 you can work on this issue

**Comment by aaryahjolia** [comment]
Can I work on this issue ?

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by Dharmesh177** [comment]
i would like to work on this
