### ISSUE TITLE
[FEATURE] Improve navbar of website

### ISSUE THREAD

**Issue by Areebah03** [The-Shivam-garg/BigB-E-learn-Websit-e#274]
### Description

I want to improve the UI of  navbar of the website. Please assign it to me @The-Shivam-garg .

### Screenshots

![ss6](https://user-images.githubusercontent.com/85051124/161943741-dde13b73-6462-4b46-83c2-3cfdf7fd84fe.png)

**Comment by The-Shivam-garg** [comment]
you can start working on the issue @Areebah03
