### ISSUE TITLE
Create a new UI for Course Page

### ISSUE THREAD

**Issue by Kumar-laxmi** [The-Shivam-garg/BigB-E-learn-Websit-e#275]
### Description

We can see that the Course Page currently looks like this:
![image](https://user-images.githubusercontent.com/76027425/161987743-5f6c1e0d-4f52-4beb-971d-d241b0e1028a.png)

which probably doesn't look good

So a new UI ,may be required

**Comment by The-Shivam-garg** [comment]
The issue is already their @Kumar-laxmi  .Check out #107
