### ISSUE TITLE
Feature : Add a "Teach on Bigb" Page

### ISSUE THREAD

**Issue by soujo** [The-Shivam-garg/BigB-E-learn-Websit-e#28]
Hi @The-Shivam-garg , As your website has a GET NEW SKILL section. So for that purpose, there should also be teachers to provide the skills. 
How about we create a landing page for those teachers who want to teach on Bigb and in the future, you could extend this section with the back-end too.
If this idea looks appropriate to you then I can work on that page under JWOC.

**Comment by The-Shivam-garg** [comment]
Sounds cool! .
 you can start working on this issue . I will officially assign this issue
to you in few hours.

**Comment by soujo** [comment]
Okay, then I am starting the work.

**Comment by soujo** [comment]
Hi @The-Shivam-garg , As I am making a new page for the teachers, it needs to be redirected from the home page.
For that, the navbar would be the best option but already it has 7 buttons so it will look bad if we push the new button over there.
Instead, can we change the `Discover Edcademy` with `Want to teach?` and then use the `find out more` for the redirect button?
Is that fine or do you have other plans for that section?
Refer to that below image

![Screenshot (196)](https://user-images.githubusercontent.com/78646418/152300219-01aaf436-c792-4911-b2ee-534253053e54.png)

**Comment by The-Shivam-garg** [comment]
Hey thanks for letting me know,
Yeah you can go with it.

**Comment by soujo** [comment]
Hi @The-Shivam-garg , Kindly see the screenshots and give feedback. What should I improve ?

![Screenshot (192)](https://user-images.githubusercontent.com/78646418/152337341-ef2d13b0-68cc-44a8-8efa-defa2763fe19.png)
![Screenshot (193)](https://user-images.githubusercontent.com/78646418/152337320-609716bc-3efd-4fc9-84a4-5263ceb7672b.png)
![Screenshot (194)](https://user-images.githubusercontent.com/78646418/152337328-43128152-a1d0-4370-ac70-cf13a6b33c81.png)
![Screenshot (195)](https://user-images.githubusercontent.com/78646418/152337336-9327b277-ee1a-4576-8d9a-74e316ffdb63.png)

**Comment by The-Shivam-garg** [comment]
Awesome!! Just do one more thing. After the review section add the variety of courses also, related to academic and non-academic (personal-development , spirituality , finance, startup .....) which can be selected by the teacher/faculty.

**Comment by soujo** [comment]
Sure, i will work on that.

**Comment by soujo** [comment]
Hi @The-Shivam-garg , Kindly check is this what you were asking for?

P.S : The illustration is created in canva 

![Screenshot (197)](https://user-images.githubusercontent.com/78646418/152385110-9e884511-7c3c-4776-b283-1676841f47dd.png)

**Comment by The-Shivam-garg** [comment]
![image](https://user-images.githubusercontent.com/83035995/152553577-a189b874-0f65-4812-8fab-f63b92d092ea.png)
@soujo i think their is an error in this have a look to it

**Comment by soujo** [comment]
I am so sorry, I forgot to push the illustration itself in the code. 
Do I have to create a new PR for the merge ? @The-Shivam-garg

**Comment by The-Shivam-garg** [comment]
Fine do it .
