### ISSUE TITLE
Feature Page syncing to repo design

### ISSUE THREAD

**Issue by Kumar-laxmi** [The-Shivam-garg/BigB-E-learn-Websit-e#283]
### Description

In the feature page we can see that the this page isn't matching the  header and footer design like other pages, so I can sync it like other pages

### Screenshots

![image](https://user-images.githubusercontent.com/76027425/162114454-ed8ea5d5-ad53-456c-b7a7-b051c94fefd2.png)
![Uploading image.png…]()

**Comment by sakshamgurbhele** [comment]
@Kumar-laxmi sure sounds good. go ahead 👍🏼
