### ISSUE TITLE
sign in page glitch

### ISSUE THREAD

**Issue by leesha19** [The-Shivam-garg/BigB-E-learn-Websit-e#288]
### Description

in  sign in page the password eye button is not styled properly

### Screenshots

![Uploading Screenshot.png…]()

**Comment by The-Shivam-garg** [comment]
Hey @leesha19 You can work on this issue !

**Comment by The-Shivam-garg** [comment]
> Hey @sakshamgurbhele , I am a GSSOC'22 contributor . Can you please assign this issue to me and add GSSOC label to it . I have send the PR #303 . You can review and merge it .

Hey @Rishita489 its a warning for you , don't take other issues and please before  assigning the issue , if you again make any PR we will take a strict action against you

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , if no one is working on this issue can you assign it to me . I am a GSSOC'22 contributor .

**Comment by The-Shivam-garg** [comment]
Sure rishita you can start working on it

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , I have send the PR . You can review and merge it .
