### ISSUE TITLE
Smooth Hover transition in homepage

### ISSUE THREAD

**Issue by XZANATOL** [The-Shivam-garg/BigB-E-learn-Websit-e#292]
### Description

Smoothen the hover transition in `What we offer` section in the home page to make it more responsive and give a better rate review to the UI.

### Screenshots

![image](https://user-images.githubusercontent.com/64689436/162528736-2861bb7b-c2b3-487d-816d-72dd19213e20.png)

Issue made under GSSoC'22 contributions.

**Comment by sakshamgurbhele** [comment]
go ahead @XZANATOL
