### ISSUE TITLE
Improve behavior in counter cards

### ISSUE THREAD

**Issue by XZANATOL** [The-Shivam-garg/BigB-E-learn-Websit-e#293]
### Description

Improve the demonstration behaviour in counter cards in `homepage > WORLD-CLASS LEARNING` section. as shown in this video

https://user-images.githubusercontent.com/64689436/162529292-b861bc81-64df-46e4-9c96-d59b945f5e2c.mp4

### Screenshots

![image](https://user-images.githubusercontent.com/64689436/162529455-b543981f-666b-4c05-9a1f-b4a0f2369813.png)

Issue made under GSSoC'22 contributions.

**Comment by sakshamgurbhele** [comment]
@XZANATOL you can Go ahead, Assigning it to you under Gssoc
