### ISSUE TITLE
Add more relevant courses in the Course page

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#3]
**Description**
_Add relevant courses to the page_

👀 Have you spent some time to check if this issue has been raised before?

- [ ]  I checked and didn't find similar issue

🏢 Have you read the Code of Conduct?

- [ ]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/0f4ca31df60cfec053eecc2027c9c6be05f4563a/CODE_OF_CONDUCT.md)

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
Thank you for showing your interest in this issue .  I'm assigning this issue to you @codervivek5 
Best wishes for your future contribution in this website.😊

**Comment by barnik109** [comment]
I want to work on this issue underJWOC.

**Comment by The-Shivam-garg** [comment]
sure @barnik109

**Comment by barnik109** [comment]
Can you please tell me more details about it?what courses,where to add.

**Comment by The-Shivam-garg** [comment]
in the course page , you can visit the different courses mention their and
can come up with any such course either in academic or
non-academic(startups,personal-development,entrepreneur,Sprituality )

**Comment by sayan404** [comment]
I  Want to work in this issue under JWOC . @The-Shivam-garg

**Comment by Mohit-1909** [comment]
Sir I would like to work on this under GSSOC

**Comment by Mohit-1909** [comment]
Is this issue still open I would like to work on it under GSSoC

**Comment by Mohit-1909** [comment]
Thank You sir I'll start working on this.

**Comment by Mohit-1909** [comment]
@The-Shivam-garg  I placed a pr #155 please check it out. Also wanted a suggestion that I wanted to add NEET course in it as there is one for JEE, is it okay to do so? cause it would ne also added in header of the course section. So should I go ahead with this idea?

**Comment by The-Shivam-garg** [comment]
> @The-Shivam-garg I placed a pr #155 please check it out. Also wanted a suggestion that I wanted to add NEET course in it as there is one for JEE, is it okay to do so? cause it would ne also get added in header of the course section. So should I go ahead with this idea? Please confirm!!

yeah you can go with this

**Comment by Mohit-1909** [comment]
Okay sir I'll start working in this.

**Comment by Mohit-1909** [comment]
![Screenshot (105)](https://user-images.githubusercontent.com/92212063/157212647-efe52445-925a-4f0f-af6e-1a406de453a1.png)
@The-Shivam-garg Can you help me with this, I cannot push my changes.
