### ISSUE TITLE
Feature: ADD a section in readme.md for showing the contributors .

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#30]
AS I Believe  : The power of Open Source is the power of the people.

**Comment by ronitblenz** [comment]
I want to work on this issue, I have past experience of 3 contributions and 8 hackathons.
Could you please add me as an assignee

Thanks and Regards

**Comment by The-Shivam-garg** [comment]
Thank you all of you for showing your interest in this issue . But for now being I'm assigning this issue to @aadrikasingh18 because of earlier comment. Other's can explore the website .
Best wishes for your future contribution in the Open-source.😊

**Comment by ronitblenz** [comment]
Sure, I will do it, if deadline crosses

**Comment by The-Shivam-garg** [comment]
Hey @aadrikasingh18 can you please share the screenshot of your code output . So it will be much easier , to know about the location where you added that section.

**Comment by aadrikasingh18** [comment]
Sure

![Screenshot (15476)](https://user-images.githubusercontent.com/91376920/152286975-c94f5f18-0099-4d6d-8d7c-09e460bbe021.png)

The highlighted portion is the part that I have added.

**Comment by The-Shivam-garg** [comment]
Thank you @aadrikasingh18 , for resolving out the issue. i have merged your code into the repository.
