### ISSUE TITLE
Smoothen Hover effect on Social Media Links

### ISSUE THREAD

**Issue by XZANATOL** [The-Shivam-garg/BigB-E-learn-Websit-e#306]
### Description

Smoothen the hover transition in `Footer > Social Media Links` section in the home page to make it more responsive and give a better rate review to the UI.

### Screenshots

![image](https://user-images.githubusercontent.com/64689436/163173630-733be35b-b6e0-4ef7-aed8-b05c50e73550.png)

Issue made under GSSoC'22 contributions.

**Comment by XZANATOL** [comment]
@sakshamgurbhele Can I get working on this?

**Comment by The-Shivam-garg** [comment]
Hey @XZANATOL you can start working on this issue !

**Comment by XZANATOL** [comment]
@The-Shivam-garg Ok, can I get working on #291 too?
