### ISSUE TITLE
Refactor Navigation Bar

### ISSUE THREAD

**Issue by XZANATOL** [The-Shivam-garg/BigB-E-learn-Websit-e#307]
### Description

Navigation bar has alot of visiual bugs that also results on bad user experience when scrolling down the page. My solution is to use flex box to refactor and correctly align navbar items. 

### Screenshots

![image](https://user-images.githubusercontent.com/64689436/163177100-cda1bf00-66c1-455c-9d08-317de87112da.png)

Issue made under GSSoC'22 contributions.

**Comment by The-Shivam-garg** [comment]
Hey @XZANATOL you can start working on this issue !
