### ISSUE TITLE
[FEATURE] Scroll to top button in courses page

### ISSUE THREAD

**Issue by Siddhesh777** [The-Shivam-garg/BigB-E-learn-Websit-e#308]
### Description

I would like to create a button which will take user to the top of the page in courses page.

I am contributor at GSSOC'22.
Please assign this issue to me.

### Screenshots

![1](https://user-images.githubusercontent.com/77476772/163180562-acf9fc8f-1cb5-4d0d-b7a0-12552dcfb2c8.png)

**Comment by The-Shivam-garg** [comment]
Hey @Siddhesh777 you can start working on this issue
