### ISSUE TITLE
Making the horizontal Navbar in Courses page.

### ISSUE THREAD

**Issue by Siddhesh777** [The-Shivam-garg/BigB-E-learn-Websit-e#309]
### Description

The Navbar in the[ COURSES](url) page is very much confusing (as it is vertical and user doesn't know the meaning of the icons)

For the reason we had created an extra field namely explore which is unnecessarily making the page longer.
I would like to create a simple navbar just like homepage which will be user friendly.

I am contributor at GSSOC'22.
Please assign this issue to me.

### Screenshots

![1](https://user-images.githubusercontent.com/77476772/163182271-79de8102-6927-40fc-ad1f-29d41da515f3.png)

**Comment by The-Shivam-garg** [comment]
you can start working on this issue

**Comment by Siddhesh777** [comment]
hey @The-Shivam-garg 
Can you please reiview this PR

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?
