### ISSUE TITLE
[FEATURE] Aligning the Signin and toggle button properly.

### ISSUE THREAD

**Issue by Siddhesh777** [The-Shivam-garg/BigB-E-learn-Websit-e#319]
### Description

the buttons of sign in and toggle mode is overlapping
I would like to add the singup button navbar and align the toggle butoon properly

I am contributor at gssoc'22
Please assign this issue to me.

### Screenshots

![1](https://user-images.githubusercontent.com/77476772/163604585-c69174f4-ed85-4813-b4b5-77c9430e7cc0.png)

**Comment by Siddhesh777** [comment]
@The-Shivam-garg 
Please assign

**Comment by The-Shivam-garg** [comment]
It's already assigned , don't create duplicate issue which are already their
