### ISSUE TITLE
The details sould be renderd even on clicking on the heading.

### ISSUE THREAD

**Issue by Siddhesh777** [The-Shivam-garg/BigB-E-learn-Websit-e#320]
### Description

It is quite frustrating that every time user need to click on the learn more button.
Instead the details page should get rendered even after clicking on the heading and paragraph.

I am contributor at GSSOC'22.
Please assign this issue to me.

### Screenshots

![1](https://user-images.githubusercontent.com/77476772/163605432-5295aea2-f278-4eab-a7dd-075e4cd116ed.png)

**Comment by The-Shivam-garg** [comment]
Hey @Siddhesh777 you can work on this issue but in addition to this please align the learn more button into the center too
