### ISSUE TITLE
[FEATURE] Make NavigationBar responsive on mobile devices

### ISSUE THREAD

**Issue by XZANATOL** [The-Shivam-garg/BigB-E-learn-Websit-e#324]
### Description

Current NavigationBar has visual bugs when viewing the site on a mobile device as shown below. I would like to edit it to make it responsive with mobile devices.

### Screenshots

Current view on a mobile device:
![image](https://user-images.githubusercontent.com/64689436/164065767-2c530397-278d-4794-b63a-3ed8bd16faa3.png)

Issue made under GSSoC'22 contributions.

**Comment by The-Shivam-garg** [comment]
hey @XZANATOL you can start working on this issue
