### ISSUE TITLE
[FEATURE] <Improvement in UI of Courses Page>

### ISSUE THREAD

**Issue by dee-ksha** [The-Shivam-garg/BigB-E-learn-Websit-e#327]
### Description

Hey, I am a GSSoc'22 participant. I noticed that there are a few alignment issues in the courses page and the text is not visible as it is overshadowed by the dark background. I would like to suggest a few modifications. Please allow me to contribute to this page. 

### Screenshots

<img width="942" alt="ss4" src="https://user-images.githubusercontent.com/77492052/164278499-0a60e6fd-c0d6-422d-a354-1bfcd2fb51d4.PNG">
<img width="946" alt="ss3" src="https://user-images.githubusercontent.com/77492052/164278510-ed8e26f0-2363-4d04-918f-e5c6731cf810.PNG">
<img width="958" alt="ss1" src="https://user-images.githubusercontent.com/77492052/164278539-44b1cec1-6446-41e7-a9f8-ea2b17a5134e.PNG">

**Comment by The-Shivam-garg** [comment]
hey @dee-ksha you can start working on this issue

**Comment by BabyElias** [comment]
@The-Shivam-garg ,If this issue hasn't been worked upon yet, I am interested in taking this up.
