### ISSUE TITLE
Improvement in Testimonial section

### ISSUE THREAD

**Issue by hs-07** [The-Shivam-garg/BigB-E-learn-Websit-e#329]
### Description

Wanted to  make the testimonial section more focused over the testimonial as ccurrently the background is looking more punchy.
I will give an effect to make the section more attractive and premium.

### Screenshots

![Screenshot (3)](https://user-images.githubusercontent.com/87127387/164287872-ce2414e8-0448-4fdf-a555-36d71a8ec65a.png)

**Comment by The-Shivam-garg** [comment]
Hey @hs-07 you can start working on this issue
