### ISSUE TITLE
Make button links redirect to their actual page on feature page

### ISSUE THREAD

**Issue by Pranai2518** [The-Shivam-garg/BigB-E-learn-Websit-e#331]
### Description

The buttons which are there on the feature page should redirect to their actual page on the website.
I would like to work on the issue. Assign me!

### Screenshots

![1](https://user-images.githubusercontent.com/75829770/164299497-517372c6-8de6-4c0f-a53e-137983242207.png)
![2](https://user-images.githubusercontent.com/75829770/164299510-fc9504b7-95b7-4e2d-b938-02ddefe77cf5.png)
![3](https://user-images.githubusercontent.com/75829770/164299512-43feb384-d3a2-4803-afbe-3990bbd296a9.png)
![4](https://user-images.githubusercontent.com/75829770/164299517-5927ed0f-af89-4033-bf99-f3db0381ad61.png)

**Comment by The-Shivam-garg** [comment]
Hey @Pranai2518 you can start working on this issue
