### ISSUE TITLE
Main content and the header were merge

### ISSUE THREAD

**Issue by Pranai2518** [The-Shivam-garg/BigB-E-learn-Websit-e#334]
### Description

The main content on the main page was combined with the header. 
I would like to make it in a proper alignment. Assign me!

### Screenshots

![1](https://user-images.githubusercontent.com/75829770/164385066-0b5e9919-7d0d-48e7-b24a-2b42095d85bc.png)

**Comment by The-Shivam-garg** [comment]
Hey @Pranai2518 you can start working on this issue
