### ISSUE TITLE
Make the Navbar Responsive 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#336]
### Description

Hey Contributors,
In this project i found out that the Navbar is not responsive due to which their is a hinderance in user experience .
we want from you is that you make the navbar of all pages responsive starting from Home page to Contact page

**Comment by XZANATOL** [comment]
@The-Shivam-garg I'm actually working on this in issue #324 . Should be finished by EOD.
