### ISSUE TITLE
[FEATURE] Adding navbar in feature section

### ISSUE THREAD

**Issue by Areebah03** [The-Shivam-garg/BigB-E-learn-Websit-e#342]
### Description

Feature section of website does not have navbar. I want to add navbar. Please assign it to me @The-Shivam-garg 

### Screenshots

![ss](https://user-images.githubusercontent.com/85051124/164986942-e61524d0-c8c7-4e6d-90df-2157204c9dca.png)

**Comment by The-Shivam-garg** [comment]
Hey @Areebah03 you can start working on this issue
