### ISSUE TITLE
[FEATURE] Improve subscribe section

### ISSUE THREAD

**Issue by Areebah03** [The-Shivam-garg/BigB-E-learn-Websit-e#357]
### Description

I want to improve subscribe section by improving button, fonts. Please assign it to me @The-Shivam-garg

 

### Screenshots

![ss](https://user-images.githubusercontent.com/85051124/165915917-d779c1bf-c343-45b9-b00d-d455d467ffb4.png)

**Comment by The-Shivam-garg** [comment]
Hey @Areebah03  you can start working on this issue
