### ISSUE TITLE
Contact Us Button on feature page not working

### ISSUE THREAD

**Issue by MonarchGitHub** [The-Shivam-garg/BigB-E-learn-Websit-e#360]
### Description

I want to update the contact us page on the features page so that it will redirect to the correct link instead of null.
Kindly assign me this under Gssoc.

### Screenshots

This is the contact us button that is not working properly.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/74449136/166073373-116c1e81-6c72-4fff-b754-bd58ea5e32e4.png">

**Comment by Pranai2518** [comment]
Hey @MonarchGitHub It is working fine.

**Comment by MonarchGitHub** [comment]
Hi, Thanks for verifying, I think the button didn't redirect cuz of connectivity issues. I tried now again and it's working fine 👍
