### ISSUE TITLE
[FEATURE] Refactor footer in courses page

### ISSUE THREAD

**Issue by XZANATOL** [The-Shivam-garg/BigB-E-learn-Websit-e#363]
### Description

Current Footer page has visual bugs, unorganized paddings & text alignments, which creates a bad review for a User Interface. I would like to refactor this part.

### Screenshots

![image](https://user-images.githubusercontent.com/64689436/166124901-3222610c-dad2-4d71-8b97-00f2d279083d.png)

Issue made under GSSoC'22 contributions.

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by XZANATOL** [comment]
I'm already working on it.
