### ISSUE TITLE
Redesign teach page

### ISSUE THREAD

**Issue by Adhetya** [The-Shivam-garg/BigB-E-learn-Websit-e#367]
### Description

The UI is not looking very good. Font should be changed along with some styling. I would like to redesign this page to give it a better look.

I am a GSSOC 22 contributor. Please assign this issue to me

### Screenshots

<img width="1440" alt="Screenshot 2022-05-05 at 8 34 31 PM" src="https://user-images.githubusercontent.com/20537150/166954009-0a21b218-f418-475b-801b-8970720a342c.png">

**Comment by The-Shivam-garg** [comment]
Hey @Adhetya you can start working on this issue
