### ISSUE TITLE
Wrong Email id in the footer section

### ISSUE THREAD

**Issue by kusumita29** [The-Shivam-garg/BigB-E-learn-Websit-e#369]
### Description

The email id provided at the footer of every page is wrong. I would like to work on it under GSSoC '22.

Please assign me this issue.

### Screenshots

<img width="960" alt="Screenshot (573)" src="https://user-images.githubusercontent.com/99873488/167083745-dbbcf434-251e-4a63-9641-2eeb304dae27.png">

**Comment by The-Shivam-garg** [comment]
Yeah you can start working on it
