### ISSUE TITLE
Template text in the Sign up section is not modified

### ISSUE THREAD

**Issue by kusumita29** [The-Shivam-garg/BigB-E-learn-Websit-e#376]
### Description

The template text in the Sign-up and Sign-in section is not modified. Relevant and brief information needs to be added there. 

I would like to work on it under GSSoC '22

### Screenshots

<img width="960" alt="Screenshot (586)" src="https://user-images.githubusercontent.com/99873488/167438433-74159171-3854-426d-8c45-5c2e41097552.png">
<img width="960" alt="Screenshot (587)" src="https://user-images.githubusercontent.com/99873488/167438444-cb7c33fb-7b24-414e-affa-b1066b2ce84f.png">

**Comment by The-Shivam-garg** [comment]
Hey @kusumita29 you can start working on this issue
