### ISSUE TITLE
Make button on sign in before hover

### ISSUE THREAD

**Issue by Pranai2518** [The-Shivam-garg/BigB-E-learn-Websit-e#377]
### Description

Make the button for sign in before hovering. To look UI good.
Assign me this issue. I'll work on it.

### Screenshots

![1](https://user-images.githubusercontent.com/75829770/167472439-6eceddab-71f1-40e3-a07c-6e6ff16bf273.png)

**Comment by The-Shivam-garg** [comment]
hey @Pranai2518 you can start working on this issue

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by The-Shivam-garg** [comment]
Sure you can start working on it
