### ISSUE TITLE
Adding Git and Github Resources in Computer Courses

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [The-Shivam-garg/BigB-E-learn-Websit-e#378]
### Description

Git and Github are one of the most widely used tools these days in computer science.

It will be relevant to add them to the computer courses.

**Comment by The-Shivam-garg** [comment]
Sure ! You can start working on it

**Comment by Sabyasachi-Seal** [comment]
Thanks a lot @The-Shivam-garg I will start working immediately.

I will be making the contribution under GSSoC. Could you add the tag ?

**Comment by Sabyasachi-Seal** [comment]
Pull Request: https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/pull/380
