### ISSUE TITLE
Horizontal navbar in all pages

### ISSUE THREAD

**Issue by aaryahjolia** [The-Shivam-garg/BigB-E-learn-Websit-e#379]
### Description

The vertical navbar in some pages like course are not so easy to navigate. Having horizontal navbar in all the pages will improve the UI of the website.

**Comment by The-Shivam-garg** [comment]
Hey @aaryahjolia you can start working on this issue

**Comment by nik132-eng** [comment]
if this issue is still open I want to work on this issue. can you please assign me this issue? for GSSoC

**Comment by aaryahjolia** [comment]
Actually I'm working on this issue @nik132-eng . If you don't see a PR in 4-5 days, then you will get assigned.

**Comment by navyasharma0203** [comment]
I would like to work on this issue. Can you assign this to me?

**Comment by The-Shivam-garg** [comment]
sure @aaryahjolia you can continue your work on this .I will confirm with you before assigning to another contributor so dont worry 

> Actually I'm working on this issue @nik132-eng . If you don't see a PR in 4-5 days, then you will get assigned.
