### ISSUE TITLE
[FEATURE] Refactor Teams Page

### ISSUE THREAD

**Issue by XZANATOL** [The-Shivam-garg/BigB-E-learn-Websit-e#387]
### Description

Teams page has some classic elements beside the modern view. I would like to re-build these parts. Changes will include:

* Adjusting font & font-size
* Adding animation
* Imrpoving UI

### Screenshots

![image](https://user-images.githubusercontent.com/64689436/168493597-f5885c28-1686-45b1-b392-395717739f5a.png)

Issue made under GSSoC'22 contributions.

**Comment by The-Shivam-garg** [comment]
hey @XZANATOL you can start working on this issue
