### ISSUE TITLE
[FEATURE] Refactor Contact Page

### ISSUE THREAD

**Issue by XZANATOL** [The-Shivam-garg/BigB-E-learn-Websit-e#391]
### Description

Contact page has some visual bugs and unorganized elements in it's body which results in a bad UI. I would like to take part in adjusting these. Changes will include:

* Correctly positioning elements.
* adjust some animations behavior.
* adding shadows to contact cards to be visible in light theme
* other UI improvments

### Screenshots

![image](https://user-images.githubusercontent.com/64689436/168934282-62842631-4288-4cb2-afe0-5469db9e3dbf.png)

Issue made under GSSoC'22 contributions.

**Comment by The-Shivam-garg** [comment]
hey @XZANATOL you can start working on this issue
