### ISSUE TITLE
Add social links in course pages

### ISSUE THREAD

**Issue by Pranai2518** [The-Shivam-garg/BigB-E-learn-Websit-e#392]
### Description

Since there are no social links added in the footer of every course page. I would like to add them. Assign me.

### Screenshots

![f1](https://user-images.githubusercontent.com/75829770/168967379-a0d343ef-bea4-476c-a7c6-983c8eb73271.png)

**Comment by The-Shivam-garg** [comment]
hey @Pranai2518  you can start working on this issue
