### ISSUE TITLE
[FEATURE] Matching footer sections

### ISSUE THREAD

**Issue by XZANATOL** [The-Shivam-garg/BigB-E-learn-Websit-e#394]
### Description

I would like to refactor the footer section in the contact page to be like the one in the courses page, as both share the same template, so It would be a bonus rate for the UI rating.

### Screenshots

![image](https://user-images.githubusercontent.com/64689436/169423667-da6a75a8-1434-4e8c-abf8-d8770f72fa28.png)

![image](https://user-images.githubusercontent.com/64689436/169423696-c67f222b-bf61-4e12-8f72-af3be8376b1b.png)

Issue made under GSSoC'22 contributions.

**Comment by Abhilasha-Jairath** [comment]
I would like to work on this issue under GSSoC 2022. Please assign this issue to me.

**Comment by The-Shivam-garg** [comment]
hey @XZANATOL  you can start working on this issue
