### ISSUE TITLE
Fixed UI of navbar

### ISSUE THREAD

**Issue by Areebah03** [The-Shivam-garg/BigB-E-learn-Websit-e#395]
### Description

I want to improve UI of navbar. Leafy border of hover effect is not looking so good. I want to enhance it. Please assign it to me @The-Shivam-garg 

### Screenshots

![ss1](https://user-images.githubusercontent.com/85051124/169479431-088bc557-bffa-4fc8-b0ec-5685cea187ba.png)

**Comment by The-Shivam-garg** [comment]
hey @Areebah03 you can start working on this issue
