### ISSUE TITLE
Improving Header of community page

### ISSUE THREAD

**Issue by Dharmesh177** [The-Shivam-garg/BigB-E-learn-Websit-e#397]
### Description

I will improve the UI of the community page and also give better look to the main section for looking osm website. Kindly assign this issue to me so I can work on it @shivam

### Screenshots

![image](https://user-images.githubusercontent.com/77879603/169677999-71895182-5f72-41a4-84bf-899865464033.png)

**Comment by Dharmesh177** [comment]
Hey @The-Shivam-garg assign this issue to me under gssoc'22 such that I can start contributing

**Comment by The-Shivam-garg** [comment]
hey @Dharmesh177 can you share the changes you are going to implement to the main section , as it is not clear from the description you have given

**Comment by Dharmesh177** [comment]
yeah sure

**Comment by Dharmesh177** [comment]
![image](https://user-images.githubusercontent.com/77879603/169680762-6f13007a-dfba-495d-a80d-f34e515d5712.png)

here left side some padding and in the header, I think to give some cool hover effect

![image](https://user-images.githubusercontent.com/77879603/169680793-84663e6f-fcc2-44ec-9d5d-d33e161ada90.png)

here you can see it is sliding for that I will try to fix it.

**Comment by The-Shivam-garg** [comment]
ohk @Dharmesh177 you can start working on this issue

**Comment by Ravina-Deogadkar** [comment]
If this issue is still open can I work on this?

**Comment by The-Shivam-garg** [comment]
Hey @Ravina-Deogadkar , sorry the issue is already resolved .Thanks for your interest in the project , you can explore other issues .

**Comment by The-Shivam-garg** [comment]
Hey let me know the short description of the changes you are going to
implement in the main section
