### ISSUE TITLE
Improve the design of contact us page

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#4]
### 👀 Have you spent some time to check if this issue has been raised before?

- [ ]  I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [ ]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/0f4ca31df60cfec053eecc2027c9c6be05f4563a/CODE_OF_CONDUCT.md)

**Comment by Ashwani-Verma-07** [comment]
hi @The-Shivam-garg  can you assign this issue to me

**Comment by The-Shivam-garg** [comment]
sure

**Comment by combatantash** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
@Ashwani-Verma-07 due to delay ,I am now assigning this issue to @combatantash

**Comment by The-Shivam-garg** [comment]
sure, @riiyaaa you can start working on this issue.
