### ISSUE TITLE
Refactor footer in feature page

### ISSUE THREAD

**Issue by Pranai2518** [The-Shivam-garg/BigB-E-learn-Websit-e#402]
### Description

Refactor the footer on the feature page.
* The current footer doesn't have the correct alignment of text and spacings.
* I would like to recreate it according to the footers on other pages. (Assign me this issue.)

### Screenshots

![1](https://user-images.githubusercontent.com/75829770/169897171-33ed08d7-a9ef-4b32-9f08-7fd3806d0bd7.png)

**Comment by The-Shivam-garg** [comment]
Hey @Pranai2518 you can start working on this issue
