### ISSUE TITLE
Alignment of the options in the navbar  is not proper in the blogs page in mobile responsive view 

### ISSUE THREAD

**Issue by Rishita489** [The-Shivam-garg/BigB-E-learn-Websit-e#403]
### Description

The options should be aligned one below the other so that it looks good with the UI .

### Screenshots

![image](https://user-images.githubusercontent.com/73689669/169951029-f51940e8-3b71-4870-a52f-3490499f1ee6.png)

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , can you please assign this issue to me and add the GSSOC label . I am a GSSOC'22 contributor .

**Comment by The-Shivam-garg** [comment]
Hey @Rishita489 you can start working on this issue

**Comment by AD1TYA03** [comment]
if it's still not fixed , assign it it to me . I will get it done.

**Comment by Ayushrawat-cmd** [comment]
is this still open?

**Comment by zaidsidd360** [comment]
Hey @The-Shivam-garg if it's still open, could you please assign it to me?

**Comment by The-Shivam-garg** [comment]
No it's not
