### ISSUE TITLE
Logo clicks not working

### ISSUE THREAD

**Issue by dheerajrao20** [The-Shivam-garg/BigB-E-learn-Websit-e#404]
### Description

While clicking on logo in some segments of website it is not returning to home page.
It is showing 404 error.
Maybe some links are missing.

@The-Shivam-garg 
Assign this issue to me I will fix it.

### Screenshots

![01 (2)](https://user-images.githubusercontent.com/89007097/170275789-179d4c8c-a724-499c-8acf-c1b6e2e11cf2.png)

**Comment by The-Shivam-garg** [comment]
hey @dheerajrao20 you can start working on this issue
