### ISSUE TITLE
Fix navbar in course and contact page

### ISSUE THREAD

**Issue by Pranai2518** [The-Shivam-garg/BigB-E-learn-Websit-e#420]
### Description

The navbar on the course page and on the contact page was not correctly aligned.
@The-Shivam-garg Assign me this issue.

### Screenshots

![1](https://user-images.githubusercontent.com/75829770/171161249-589a1980-c9a5-4adb-9e3a-fd685277e11d.png)

![2](https://user-images.githubusercontent.com/75829770/171161260-d4270e30-ed93-4ef2-b18b-75c78fd7df55.png)

**Comment by The-Shivam-garg** [comment]
hey @Pranai2518 you can work on this issue

**Comment by Pranai2518** [comment]
Hey @The-Shivam-garg, Can I work on this issue?

**Comment by The-Shivam-garg** [comment]
Hey pranai thanks for your active contribution in this project .

Actually the GSSoc is ended now , so you cant work on it under GSSoC
program. But if you want to do it  on the volunterry basis then i would
love to assign this issue to you

**Comment by Pranai2518** [comment]
Hey @The-Shivam-garg. I don't want it like to work under GSSoC to get the points. I Just want to complete this issue because I've raised it.

**Comment by The-Shivam-garg** [comment]
Great then , will assign you the issue in a while . You can start working
on the issue :)
