### ISSUE TITLE
Unwanted commented codes

### ISSUE THREAD

**Issue by codeknight1** [The-Shivam-garg/BigB-E-learn-Websit-e#430]
### Description

Unwanted commented codes should be removed from a web page because it might mistakenly uncommented and turn into a bug...

**Comment by Shamik1836** [comment]
Can I work on this issue, if it's still open?

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of project in past and has a great experience.
