### ISSUE TITLE
[FEATURE] autofocus on input fields 🛠

### ISSUE THREAD

**Issue by IAmTamal** [The-Shivam-garg/BigB-E-learn-Websit-e#435]
## Changes i'd suggest  :

- `Autofocus` on the input field so that  we donot need to again click the input field to provide the detials
- I intend to make it available for all devices and all pages

## Why to bother ? 

- Using `Autofocus` is a good accessibility feature
- It provides a much premium user experience
- It would remove the pain of clicking the box again and again.

## Can i work on it  ?

**YES, i'll be glad to help an awesome Opensource project 🚀**

## Screenshots of the changes i am suggesting : 

**CHANGES WILL BE MADE TO ALL THE PAGES WITH INPUT, I JUST ADDED 1 SS INSTEAD OF ALL**

![image](https://user-images.githubusercontent.com/72851613/193630499-91e4305a-c66e-40bc-82b8-a716d13fdad2.png)

**Comment by The-Shivam-garg** [comment]
hey @IAmTamal , thanks for recommending the feature. you can start working on the same.

**Comment by IAmTamal** [comment]
@The-Shivam-garg made a PR, feel free to let me know about further changes !
