### ISSUE TITLE
[Frontend] Signup page responsiveness 🛠

### ISSUE THREAD

**Issue by IAmTamal** [The-Shivam-garg/BigB-E-learn-Websit-e#436]
## Changes i'd suggest  :

- The signup page is not responsive for mobile devices
- I can work on it to make the signup page more responsive so that it looks perfect for mobiles and smaller screens.
- You can test it out (broken signup) by visiting the signup page.

## Desktop : 

- The icon to hide and show password is out of bounds
- It can be worked out so that it is on the right side of the input fields.

## Can i work on it ? 

Sure, assign me the issue and i'll start working on it ASAP !

### Screenshots

![image](https://user-images.githubusercontent.com/72851613/193631056-5d56c576-a972-427f-9305-0bde17372540.png)
![image](https://user-images.githubusercontent.com/72851613/193631675-2f68cb3c-755e-4f47-854f-a1d092d49be4.png)

**Comment by The-Shivam-garg** [comment]
hey @IAmTamal thanks for reporting the bug , you can work on the issue

**Comment by IAmTamal** [comment]
Hey @The-Shivam-garg , the PR is  created at #456 , feel free to suggest me changes if any.
