### ISSUE TITLE
Slideshow effect doesn't work int teach.html page

### ISSUE THREAD

**Issue by pandeatul27** [The-Shivam-garg/BigB-E-learn-Websit-e#441]
### Description

The image slider doesn't change automatically, and also the third slide doesn't open even on clicking the third dot

### Screenshots

<img width="960" alt="2022-10-04 (4)" src="https://user-images.githubusercontent.com/94844506/193743485-c792657b-ba56-4c1c-83c3-7094774164f2.png">

**Comment by pandeatul27** [comment]
Allow me to work on this issue under hacktoberfest

**Comment by The-Shivam-garg** [comment]
hey @pandeatul27 , thanks for finding the bug you can start working on this issue
