### ISSUE TITLE
[Home - Responsive] what we offer section breaks layout

### ISSUE THREAD

**Issue by mohamednajiub** [The-Shivam-garg/BigB-E-learn-Websit-e#450]
### Description

the items in this section have a big font size in responsive that's another part of the issue horizontal scroll and white space on the right of screen.

**NOTE**
part one of the horizontal scroll issue mentioned in #449 

![image](https://user-images.githubusercontent.com/22493564/193952679-0013ea1d-10a4-42ed-a128-c84990761df2.png)

**Can I work on it ?**
Absolutely, assign me the issue and add hacktoberfest label I'll start working on it!

**Comment by The-Shivam-garg** [comment]
hey @mohamednajiub you can work on this issue . but the second issue that you mentioned as a different issue . Due to the changes that need to be done in both are very minimal so i will count both in one . so it will be good if you can implement both the issue in a single commit and make  a PR
