### ISSUE TITLE
Improve the testimonials section 

### ISSUE THREAD

**Issue by Anjuli08** [The-Shivam-garg/BigB-E-learn-Websit-e#451]
### Description

The testimonials section is not properly aligned in the site. so I would like to correct its alignment and make it more attractive wherever necessary under the HACTOBERFEST 2022.

### Screenshots

![bigb05](https://user-images.githubusercontent.com/90701800/193973161-a1386b7b-a8e9-43bb-b14d-d174ed3c0205.png)

**Comment by The-Shivam-garg** [comment]
hey @Anjuli08 this was done intentionally . though you can check out other issue that are listed over there
