### ISSUE TITLE
Uneven distribution in U.I

### ISSUE THREAD

**Issue by AryanSahoo-2003** [The-Shivam-garg/BigB-E-learn-Websit-e#455]
### Description

In most of the course section , uneven distribution of course amount ,it's details etc are present in different cards which make it unattractive...It can be solved by making it in a generalised order padding and constant margin.

### Screenshots

![image](https://user-images.githubusercontent.com/110082824/194109015-57511e7f-745e-4ed2-b060-31a318f17759.png)
![image](https://user-images.githubusercontent.com/110082824/194109049-3bf3e91f-549f-4671-9770-179cf7276a9c.png)

**Comment by AryanSahoo-2003** [comment]
Please assign me to this under hacktoberfest so that I can resolve this

**Comment by The-Shivam-garg** [comment]
hey @AryanSahoo-2003 , thanks for reporting the bug . you can start working on this issue
