### ISSUE TITLE
Courses Page: Alt Text on Course Images Links

### ISSUE THREAD

**Issue by marisabrantley** [The-Shivam-garg/BigB-E-learn-Websit-e#459]
### Description

On the main Courses page of the site, the images used in the boxes linked to the individual courses need alt text (let's make this site more accessible). 

Please assign this to me.

### Screenshots

<img width="596" alt="missing-alt-text" src="https://user-images.githubusercontent.com/60168324/194158783-c837ad6e-7d73-4411-af31-1b1dd32eeabc.png">

**Comment by The-Shivam-garg** [comment]
hey @marisabrantley , thanks for recommending changes . You can start working on this issue

**Comment by marisabrantley** [comment]
Thank you.
