### ISSUE TITLE
Sign in button not working on contact us page

### ISSUE THREAD

**Issue by jriyyya** [The-Shivam-garg/BigB-E-learn-Websit-e#465]
### Description

After clicking on the sign in button, a new page opens up for login, but that does not happen in contact us. After clicking on sign in button present on contact us page, it does not respond.

I believe I can fix this issue, Can you please assign this issue to me under hactoberfest tag.

**Comment by The-Shivam-garg** [comment]
hey @jriyyya thanks for finding the bug , You can start working on this issue
