### ISSUE TITLE
Boxes on the blog page are not aligned

### ISSUE THREAD

**Issue by pandeatul27** [The-Shivam-garg/BigB-E-learn-Websit-e#469]
### Description

Boxes on the blog page are unevenly aligned

### Screenshots

<img width="960" alt="2022-10-07" src="https://user-images.githubusercontent.com/94844506/194468395-19d7169e-8e94-4202-9e20-30b63306bc89.png">

**Comment by pandeatul27** [comment]
Allow me to work on this issue under hacktoberfest

**Comment by The-Shivam-garg** [comment]
hey @pandeatul27 , thanks for reporting the bug and showing your interest in working the same .You can start working on this issue
