### ISSUE TITLE
Improving Courses Page

### ISSUE THREAD

**Issue by sumitkr2000** [The-Shivam-garg/BigB-E-learn-Websit-e#471]
### Description

Hey @The-Shivam-garg, The course page is not properly alligned with the page. Can you assign me this issue so that I can fix it?

Thank you!

### Screenshots

![Screenshot (376)](https://user-images.githubusercontent.com/100675296/194602245-9b1b06ed-a795-4a74-ae42-b36d3634ca6e.png)

**Comment by The-Shivam-garg** [comment]
Hey @sumitkr2000  , thanks for your suggestion . But somebody is already working on this issue. You can look out for the other issues that are listed over there
