### ISSUE TITLE
Unattractive Blog section in Feature Tab

### ISSUE THREAD

**Issue by AryanSahoo-2003** [The-Shivam-garg/BigB-E-learn-Websit-e#481]
### Description

There is uneven flow of three blog cards which needs to be smooth so as to make it a generalized attractive card.
Also in this section, the top button is somewhat clumsy and I think it should be same which is on Home Tab

### Screenshots

![image](https://user-images.githubusercontent.com/110082824/194716346-0231e5e3-8646-4f70-a6a1-ecdf6e950f9b.png)
![image](https://user-images.githubusercontent.com/110082824/194716456-1724000e-941c-49a9-8477-b376e6b19178.png)

**Comment by The-Shivam-garg** [comment]
Hey @AryanSahoo-2003,thanks for the suggestions . You can start working on this issue .
Happy Coding :)
