### ISSUE TITLE
Day-Night Toggle icon doesn't look good.

### ISSUE THREAD

**Issue by imyoungsparda** [The-Shivam-garg/BigB-E-learn-Websit-e#484]
### Description

The sun icon in day-night toggle looks like a setting icon which confuses a new visitor of the website.

We can use this icon.

![image](https://user-images.githubusercontent.com/112796825/194724092-1ad35b0b-0a83-4fd4-9ea3-54f94f9d303c.png)

### Screenshots

![image](https://user-images.githubusercontent.com/112796825/194724067-c3862a7a-4b5f-406d-882d-cc8a84bf1acd.png)

**Comment by The-Shivam-garg** [comment]
Hey @imyoungsparda , thanks for the suggestions . You can start working on this issue .
Happy Coding :)

**Comment by imyoungsparda** [comment]
Sorry @The-Shivam-garg , The icon which I thought is not free. It's in pro version. 
I have made few changes other than this. Please review.

**Comment by ayush-Sharma173** [comment]
@The-Shivam-garg Please assign this issue to me I have written the code and ready to make PR

**Comment by Rajnish-bhagat** [comment]
@The-Shivam-garg could you assign it to me?

**Comment by singhvaishu** [comment]
hii sir 
please assign this project to me . i want to work on this  issues.
