### ISSUE TITLE
Navlinks on hover doesn't have proper padding.

### ISSUE THREAD

**Issue by imyoungsparda** [The-Shivam-garg/BigB-E-learn-Websit-e#485]
### Description

When the navlinks of the navbar is on hover state, The highlight area doesn't have proportionate padding around. The highlight on hover doesn't look good. 

### Screenshots

![image](https://user-images.githubusercontent.com/112796825/194724193-a33d93d8-8377-4557-b0c8-4c7117c3aa26.png)

**Comment by The-Shivam-garg** [comment]
Hey @imyoungsparda, i appreciate your time and efforts. But I can only merge both of your issue in a single PR as both requires minimal changes . If your Ohk with this let me know I will assign this issue to you

**Comment by imyoungsparda** [comment]
Yes, I will be doing both the changes in a single PR

**Comment by imyoungsparda** [comment]
There is one more change Shivam bhai which I can do in the same PR. 
The illustrations in Why Education section is little outside the card in desktop view.

**Comment by The-Shivam-garg** [comment]
Sure @imyoungsparda
