### ISSUE TITLE
Unattractive weird squares in buttons on the feature page

### ISSUE THREAD

**Issue by subhajitroycode** [The-Shivam-garg/BigB-E-learn-Websit-e#493]
### Description

Hi there, I've come across these weird squares in buttons on the feature page. It looks very unattractive on this page and I want to fix the issue. 

So can you assign me this problem?

### Screenshots

![image](https://user-images.githubusercontent.com/72935263/194765396-7cf19715-ca76-4d7c-a38c-ea2f5ca47c26.png)

**Comment by subhajitroycode** [comment]
Hi @The-Shivam-garg can I work on this?

**Comment by The-Shivam-garg** [comment]
Unfortunately No , actually i Won't find out this , that suitable for the changes
