### ISSUE TITLE
Footer Section in mobile layout is not properly aligned

### ISSUE THREAD

**Issue by SujalSamai** [The-Shivam-garg/BigB-E-learn-Websit-e#494]
### Description

When we switch into mobile layout, all the different parts of the footer section seems not properly aligned. They are just scattered all around. I would like to fix this issue. So can you kindly assign me this issue?

### Screenshots

![image](https://user-images.githubusercontent.com/87236576/194771868-95052bf2-8fb9-4ea4-bcd1-576b49a542ee.png)

**Comment by The-Shivam-garg** [comment]
Hey @SujalSamai , Thanks for suggesting changes ! You can start working on this issue

**Comment by simransia** [comment]
Hello @The-Shivam-garg ! Please assign me this issue, I will be happy to work on it.

**Comment by The-Shivam-garg** [comment]
Hey @simransia  , Thanks for showing your interest in contributing to the project. You can start working on this issue :)
