### ISSUE TITLE
Join Course Template

### ISSUE THREAD

**Issue by Priyanshu-Aggarwal** [The-Shivam-garg/BigB-E-learn-Websit-e#495]
In this template, user also select **SELECT THE COURSE ** in dropdown. Please assign me this issue so I remove this.

**Comment by The-Shivam-garg** [comment]
Hey @Priyanshu-Aggarwal , can you please show the section SS , about which you are talking about

**Comment by Priyanshu-Aggarwal** [comment]
![image](https://user-images.githubusercontent.com/72151968/194811968-acaa663f-08d1-4066-9a30-cda0c8dfd4f5.PNG)
![image2](https://user-images.githubusercontent.com/72151968/194812085-b2b41d79-b760-42e4-9740-b9e0f8d9b3d6.PNG)


Here, User can also select **"SELECT THE COURSE"** option. It doesn't look good that user also select the SELECT option

**Comment by The-Shivam-garg** [comment]
see , To get enrolled it's important to select the course specification . So I dont think this needs to be changed
