### ISSUE TITLE
Nav links texts doesn't appear clearly on hover.

### ISSUE THREAD

**Issue by imyoungsparda** [The-Shivam-garg/BigB-E-learn-Websit-e#498]
### Description

Nav links on pages such as courses, blogs, features and contact text colour remains black on hover which is not at all readable.

![image](https://user-images.githubusercontent.com/112796825/195137733-1448fc0c-026e-42f6-9bc9-0a9b59c22bea.png)

### Screenshots

![image](https://user-images.githubusercontent.com/112796825/195137795-84ad3539-a7ff-4763-9c6f-3f56860ec06a.png)

**Comment by abitsalihu** [comment]
Hey, I would like to help with this issue. :)

**Comment by The-Shivam-garg** [comment]
Hey @imyoungsparda , you can start working on the same
