### ISSUE TITLE
OVERLAY CLICK TO CLOSE MODAL , OVERLAY UI CHANGES

### ISSUE THREAD

**Issue by Sanket-Gawande** [The-Shivam-garg/BigB-E-learn-Websit-e#507]
### Description

when modal is popping on, its does  not closes on clicking the overlay. make it work

**Comment by The-Shivam-garg** [comment]
can you descriptive it a little bit

**Comment by Sanket-Gawande** [comment]
when the modal is up there, the only way to close it was to click on X button, ideally it needs to be closed on clicking overlay on screen.
