### ISSUE TITLE
Improve UI of "Want to teach"

### ISSUE THREAD

**Issue by Jiya-garg9971** [The-Shivam-garg/BigB-E-learn-Websit-e#509]
### Description

![image](https://user-images.githubusercontent.com/100217150/195991943-f0949da2-31e2-4505-9b43-f52a88de9038.png)

WANT TO TEACH heading does not look interactive.

### Screenshots

![image](https://user-images.githubusercontent.com/100217150/195992440-a4030b25-1180-4313-9656-3bc1b73163f4.png)

**Comment by Jiya-garg9971** [comment]
Please assign this issue to me under hacktoberfest.

**Comment by The-Shivam-garg** [comment]
Hey @Jiya-garg9971 , thanks for your suggestion . but see , the previous design is pretty simple and effective in consideration to UI . So I can't accept these changes.

**Comment by Jiya-garg9971** [comment]
No issue @The-Shivam-garg. Thanks for review.
