### ISSUE TITLE
Back to top button in contact us page

### ISSUE THREAD

**Issue by Rishita489** [The-Shivam-garg/BigB-E-learn-Websit-e#510]
### Description

I want to add back to top button in contact us page .

**Comment by Rishita489** [comment]
Hey @The-Shivam-garg , can you please assign this issue to me under Hacktoberfest 2022 .

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of project in past and has a great experience.

**Comment by The-Shivam-garg** [comment]
Hey @Rishita489 , Thanks for your suggestion. But see, User can head up to the top in just one scroll. So I don't find the need of having it
