### ISSUE TITLE
Add some changes in the navbar

### ISSUE THREAD

**Issue by bajajharsha** [The-Shivam-garg/BigB-E-learn-Websit-e#517]
## 👨‍💻 Changes proposed

- Change the font of the navbar
- Add margin 
- Change the font family of the navbar

## 📷 Screenshots
Before
![image](https://user-images.githubusercontent.com/85387921/196129644-f9f06520-b5e9-4fed-b76f-ab16b833c1b2.png)
After
![image](https://user-images.githubusercontent.com/85387921/196129758-c6a62911-ccf7-4e39-8c3d-62ee1380edee.png)

**Comment by The-Shivam-garg** [comment]
Hey you can start working on this issue , but what i want is the alignment of all the entities in the navbar to be centered as from the screenshot it seems like it has some alignment issue . Do rectify it as well!

**Comment by bajajharsha** [comment]
Okay. I will work on it.
