### ISSUE TITLE
fix for section below navbar in courses.html 

### ISSUE THREAD

**Issue by EmzB** [The-Shivam-garg/BigB-E-learn-Websit-e#521]
### Description

**The intro section below the navbar in courses.html is hidden.**
<img width="960" alt="section-nav" src="https://user-images.githubusercontent.com/16004421/197756461-99bc6f60-b535-4ec9-9a46-9b3bf4f93a3e.PNG">

**Comment by The-Shivam-garg** [comment]
Hey @EmzB , Thanks for showing your interest in contributing to the project.You can start working on this issue :)
