### ISSUE TITLE
feature:make the course pop up , responsive

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#56]

**Comment by rohit-raj25** [comment]
I want to work on this issue under JWOC.

**Comment by The-Shivam-garg** [comment]
sure @rohit-raj25 you can start working on this issue

**Comment by Shruti025** [comment]
hey can I work on this issue under JWOC?

**Comment by Shruti025** [comment]
hey @The-Shivam-garg can I work on this issue under JWOC?

**Comment by The-Shivam-garg** [comment]
sure @Shruti025 you can start working on this

**Comment by sakshamgurbhele** [comment]
Thank You @Shruti025 for your contribution, ✨😇
