### ISSUE TITLE
Add a CART!

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#6]
**Feature description**
_For those who want to read later or use later it would be great!_

👀 Have you spent some time to check if this issue has been raised before?

- [x]  I checked and didn't find similar issue

🏢 Have you read the Code of Conduct?

- [x]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/0f4ca31df60cfec053eecc2027c9c6be05f4563a/CODE_OF_CONDUCT.md)

**Comment by barnik109** [comment]
I want to work on this issue under JWOC.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
Thank you all of you for showing your interest in this issue . But for now being I'm assigning this issue to @barnik109   because of earlier comment. Other's can explore the website .
Best wishes for your future contribution in the Open-source.😊

**Comment by barnik109** [comment]
Can you please tell me the details about the of the cart?

**Comment by The-Shivam-garg** [comment]
The cart feature works the same as in any ecommerce website , where we
store what we like or want to buy..

**Comment by barnik109** [comment]
Can you please tell me which items will be added to cart ?

**Comment by barnik109** [comment]
I am designing cart for the sample books given on this site.Is it okay?

**Comment by The-Shivam-garg** [comment]
Sure

**Comment by barnik109** [comment]
$ git clone https://github.com/SauravMukherjee44/Aec-Library-Website.git
I have worked on this link and my work is completed.But the user is not giving permission .

**Comment by The-Shivam-garg** [comment]
I think you have worked on someone else project it's not BIGB-eLearning-Website

**Comment by barnik109** [comment]
It was written to clone that project so I cloned it and worked.What can I do now?

**Comment by The-Shivam-garg** [comment]
where it is mentioned ?

**Comment by barnik109** [comment]
Here under the title fork a project in highlighted text.

**Comment by The-Shivam-garg** [comment]
![image](https://user-images.githubusercontent.com/83035995/152150583-116fc10a-28b7-4784-a64d-aee0c5126491.png)
have a look to it , are you talking about this?

**Comment by barnik109** [comment]
In the code section of the github repository where you have given all the documents and basics of github and git.

**Comment by The-Shivam-garg** [comment]
ohk got it , just in a while i will be correcting then follow the same procedure . sorry for the inconvenience

**Comment by The-Shivam-garg** [comment]
sure !

**Comment by barnik109** [comment]
Thanks a lot.

**Comment by barnik109** [comment]
Can you please again tell me or show me which items will be added to cart?

**Comment by The-Shivam-garg** [comment]
for now you have to just add a icon of the cart. 
Cause their are no books and courses available that can be added to the cart

**Comment by barnik109** [comment]
okay got it.

**Comment by barnik109** [comment]
I think my code is not updated because it is not showing the cart.Can you please check and tell me?

**Comment by The-Shivam-garg** [comment]
It is updateed you can directly visit the github active page section their
you can find .

**Comment by barnik109** [comment]
Okay,got it.
