### ISSUE TITLE
BUG: Resolve the blog home page

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#62]
THIS :
![image](https://user-images.githubusercontent.com/83035995/153711442-48eb3539-47c5-4ff0-8052-a5f21a70acbf.png)

needs to be seems like this
![image](https://user-images.githubusercontent.com/83035995/153711430-f566bff9-afe7-4654-bf47-2dc4e05f1ab9.png)

**Comment by DarkFalc0n** [comment]
I want to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
sure @DarkFalc0n , You can start working on the issue.

**Comment by Shruti025** [comment]
Is this issue still unresolved @The-Shivam-garg? If yes then I can work on it under JWOC

**Comment by The-Shivam-garg** [comment]
Thank you @shruti for showing your interest in this issue , But it is
already assign to someone.and he is working on it.

**Comment by Shruti025** [comment]
okay no problem, thanks for informing :)
