### ISSUE TITLE
Improve navbar 

### ISSUE THREAD

**Issue by Srijita-Mandal** [The-Shivam-garg/BigB-E-learn-Websit-e#68]
In the website, all pages are not properly linked through navbar. Also, Navbar is not fixed at the top position. Can I work on this issue under JWOC, to improve the navbar?

**Comment by The-Shivam-garg** [comment]
sure! @Srijita-Mandal , You can work on it,

**Comment by riiyaaa** [comment]
I would like to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
thank you @riiyaaa for showing your interest in this issue , But this issue is currently allotted to someone else .I would suggest you to explore the website and come up with a creative change or some bug you want to fix.

**Comment by Shruti025** [comment]
hey @Srijita-Mandal are you working on this issue?

**Comment by Srijita-Mandal** [comment]
> hey @Srijita-Mandal are you working on this issue?

No.. I am not working now on this

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by shubhsardana29** [comment]
I am a GSSOC'22 participant, I want to work on this issue.

**Comment by The-Shivam-garg** [comment]
Sure @shubh Sardana you can start working on it. I will assign you in a
while
