### ISSUE TITLE
Improve the UI of the Blogs Section 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#7]
**Feature description**

👀 Have you spent some time to check if this issue has been raised before?

- [ ]  I checked and didn't find similar issue

🏢 Have you read the Code of Conduct?

- [ ]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/0f4ca31df60cfec053eecc2027c9c6be05f4563a/CODE_OF_CONDUCT.md)

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by The-Shivam-garg** [comment]
Thank you all of you for showing your interest in this issue . But for now being I'm assigning this issue to @whiteHatpro .
Best wishes for your future contribution in the Open-source.😊
