### ISSUE TITLE
Responsiveness bug in Contact Us and Courses Pages

### ISSUE THREAD

**Issue by Shruti025** [The-Shivam-garg/BigB-E-learn-Websit-e#76]
The content is hiding behind the navbar for smaller widths for the Contact Us and Courses Pages. 
![image](https://media.discordapp.net/attachments/936701305882284135/944257948882993212/unknown.png?width=485&height=586)
![image](https://media.discordapp.net/attachments/936701305882284135/944258284498608139/unknown.png?width=407&height=586)

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by The-Shivam-garg** [comment]
Sure !
