### ISSUE TITLE
Create a Contributors page for the website

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#8]
Create a Contributors page for the website and add each contributor with their image and Github profile.
Link the page with the home page and add it to the navbar.

👀 Have you spent some time to check if this issue has been raised before?
- [ ]  I checked and didn't find similar issue

🏢 Have you read the Code of Conduct?
- [ ]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/0f4ca31df60cfec053eecc2027c9c6be05f4563a/CODE_OF_CONDUCT.md)

**Comment by Sneha0324** [comment]
> Create a Contributors page for the website and add each contributor with their image and Github profile.
> Link the page with the home page and add it to the navbar.
> 
> 👀 Have you spent some time to check if this issue has been raised before?
> - [ ]  I checked and didn't find similar issue
> 
> 🏢 Have you read the Code of Conduct?
> - [ ]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/0f4ca31df60cfec053eecc2027c9c6be05f4563a/CODE_OF_CONDUCT.md)

I want to try this please assign me this project

**Comment by The-Shivam-garg** [comment]
sure

**Comment by Sneha0324** [comment]
Hello Shivam,
I heard that mentors can't assign issues before 1st feb.
So what should I do? Should I submit my work after 1st feb or before?
Will it be considered if submit it before 1st feb?

Sincerely,
Sneha

**Comment by The-Shivam-garg** [comment]
You can start working just submit it after 1 feb for your contribution
validity .

Best,
Shivam

**Comment by Sneha0324** [comment]
Ok

**Comment by Atif0604** [comment]
I want to work on this issue under JWOC

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by Atif0604** [comment]
Hey @The-Shivam-garg pleas assign under GSSOC'22

**Comment by sakshamgurbhele** [comment]
Hey @Sneha0324, Are you on this issue!?
