### ISSUE TITLE
CSS enhancement of subscribe section

### ISSUE THREAD

**Issue by riiyaaa** [The-Shivam-garg/BigB-E-learn-Websit-e#80]
I would like to add a hover effect on subscribe button and make the placeholder disappear when clicked on. <br>
![unknown](https://user-images.githubusercontent.com/87305761/155195457-513696be-3317-49a5-8e6a-ae1818facc49.png)

**Comment by riiyaaa** [comment]
I would like to work on it under JWOC

**Comment by The-Shivam-garg** [comment]
sure @riiyaaa you can start working on this issue
