### ISSUE TITLE
Enhancement of online course section

### ISSUE THREAD

**Issue by soujo** [The-Shivam-garg/BigB-E-learn-Websit-e#81]
Currently, the online course section ( given below ) form validation is not correct and it is done using `alert` in javascript which is not that good looking.
I want to modify the form validation and a few things using good UI error pop-up msg.
Kindly assign me this issue @The-Shivam-garg 
![Screenshot (217)](https://user-images.githubusercontent.com/78646418/155338486-bbec4285-c914-4f5b-bc3d-5e27f3103bbe.png)

**Comment by The-Shivam-garg** [comment]
sure @soujo , You can start working on this issue
