### ISSUE TITLE
Issue: Link is not behaving as expected! 

### ISSUE THREAD

**Issue by AjeetSingh2016** [The-Shivam-garg/BigB-E-learn-Websit-e#82]
Currently, On the [Contact us](https://rb.gy/s5llgz) page, Home link is not working fine it redirects to the **404** page.

I would like to resolve this issue. Please assign me on this @The-Shivam-garg

**Images**
![oss ss](https://user-images.githubusercontent.com/80536741/155386327-451bce7e-16f5-4338-a75b-1c320a80c26f.png)
 
![ss oss](https://user-images.githubusercontent.com/80536741/155386403-96319b16-348e-438e-aa8b-886d47447ba6.png)

**Comment by The-Shivam-garg** [comment]
sure @AjeetSingh2016 you can start working on this ,but please clarify this are you jwoc contributor ?

**Comment by AjeetSingh2016** [comment]
> sure @AjeetSingh2016 you can start working on this ,but please clarify this are you jwoc contributor ?

No,  i am not contributing under jwoc.

**Comment by The-Shivam-garg** [comment]
ohk cool !

**Comment by AjeetSingh2016** [comment]
There is one more issue on the Blog page, **Features** button of the navbar is not working,
Can I move further to this problem?
![ossss](https://user-images.githubusercontent.com/80536741/155600494-9376f07a-24b3-4792-832e-5546842c96c4.png)

**Comment by The-Shivam-garg** [comment]
sure you can!
