### ISSUE TITLE
Features Page Issue

### ISSUE THREAD

**Issue by Shruti025** [The-Shivam-garg/BigB-E-learn-Websit-e#83]
- The content is hiding behind the screen
- We can have hamburger menu for smaller screens

![image](https://user-images.githubusercontent.com/72005584/155463732-37365ca7-2ed9-4b78-94ce-d7e75175e61d.png)
![image](https://user-images.githubusercontent.com/72005584/155463800-3688b083-7ef8-4e8b-a859-b487a6de3fcd.png)

**Comment by Shruti025** [comment]
I want to work on this under JWOC

**Comment by The-Shivam-garg** [comment]
sure @Shruti025 you can start working on this issue
