### ISSUE TITLE
Create a feature page for the website 

### ISSUE THREAD

**Issue by The-Shivam-garg** [The-Shivam-garg/BigB-E-learn-Websit-e#9]
Create a Contributors page for the website and add each contributor with their image and Github profile.
Link the page with the home page and add it to the navbar.

👀 Have you spent some time to check if this issue has been raised before?

- [ ]  I checked and didn't find similar issue

🏢 Have you read the Code of Conduct?

- [ ]  I have read the [Code of Conduct](https://github.com/The-Shivam-garg/BigB-E-learn-Websit-e/blob/0f4ca31df60cfec053eecc2027c9c6be05f4563a/CODE_OF_CONDUCT.md)

**Comment by ishitaac** [comment]
I want to work on this issue under JWOC

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by ronitblenz** [comment]
I want to work on this.Please Let me in.

**Comment by The-Shivam-garg** [comment]
Thank you all of you for showing your interest in this issue . But for now being I'm assigning this issue to @ishitaac   because of earlier comment. Other's can explore the website .
Best wishes for your future contribution in the Open-source.😊

**Comment by The-Shivam-garg** [comment]
Hey @ishitaac are you still working on this ?

**Comment by ishitaac** [comment]
> Hey @ishitaac are you still working on this ?

Yes I'm I still have time left right

**Comment by The-Shivam-garg** [comment]
Yeah! Would you mind if i will assign this issue to one more mentee and he
will collaborate with you?

**Comment by ishitaac** [comment]
No worries you can assign another mentee, but will the points be divided then?

**Comment by ishitaac** [comment]
?
Pls confirm

**Comment by ronitblenz** [comment]
I have no problem in Collaboration... If @ishitaac agrees.

**Comment by The-Shivam-garg** [comment]
No the points will be alloted seprately to both of you

**Comment by ishitaac** [comment]
cool then, we will collaborate

**Comment by ronitblenz** [comment]
here is my discord @ronitblenz #6936
Please ping me up

**Comment by ronitblenz** [comment]
I am making a PR so that I get 5 points (minor changes)
