### ISSUE TITLE
improving "Why Education" section with better ui components 

### ISSUE THREAD

**Issue by 19arnab190201** [The-Shivam-garg/BigB-E-learn-Websit-e#93]
improving the existing design with better layout & Structure for better look and feel

**Comment by The-Shivam-garg** [comment]
Thanks @19arnab190201 for your recommendation , you can start working on this

**Comment by 19arnab190201** [comment]
Please check a your mail i have shared you the screenshots [shivanshagarwal2020@gmail.com]
Subject of mail : BigB Update(Why Edu Section)

Thank you
