### ISSUE TITLE
[Bug]: Font style in the "Blogs" page's Header portion is changing . 

### ISSUE THREAD

**Issue by sayan404** [The-Shivam-garg/BigB-E-learn-Websit-e#95]
The font style of the header portion is changing while browsing in the Blogs page only ,which is unnatural compering with the other pages 

Home page's Font style ...
![Screenshot 2022-03-01 135151](https://user-images.githubusercontent.com/95490367/156134621-0fe745c4-b95d-42e5-a888-11bb119c0a93.png)

Blogs' page's Font style  ...

![Screenshot 2022-03-01 135320](https://user-images.githubusercontent.com/95490367/156134646-5b1e6100-f49f-4fa3-8a01-fb1b45777950.png)
.

The problem is the font style of the header portion is changing only in the Blogs' page

**Comment by sayan404** [comment]
I want to work in this issue under JWOC

**Comment by The-Shivam-garg** [comment]
Thanks @sayan404  for finding the issue in documentation , you can start working on this
