### ISSUE TITLE
Improve subscribe newsletter section

### ISSUE THREAD

**Issue by AshutoshDash1999** [The-Shivam-garg/BigB-E-learn-Websit-e#96]
The subscribe newsletter doesn't look good.
 
Can I improve it? Please assign this issue to me.

![image](https://user-images.githubusercontent.com/46455250/156141423-fcf91784-0a77-4de7-b60b-4b40be48f090.png)

**Comment by The-Shivam-garg** [comment]
Thanks @AshutoshDash1999 for your recommendation , you can start working on this

**Comment by sakshamgurbhele** [comment]
Hey @AshutoshDash1999 , if you are working on this issue comment on #205.
