### ISSUE TITLE
To change the font for the "Blog" page

### ISSUE THREAD

**Issue by aishwaryas15** [The-Shivam-garg/BigB-E-learn-Websit-e#98]
The web design is good but the font needs to be changed. The change in font will definitely give a good user experience.

**Comment by The-Shivam-garg** [comment]
Thanks @aishwaryas15  for finding the recommendation , you can start working on this

**Comment by HarshKumarChoudary** [comment]
I'm GSSOC 22 contributor. If this issue is still available and not completed yet, please assign it to me. Thanks

**Comment by aishwaryas15** [comment]
> I'm GSSOC 22 contributor. If this issue is still available and not completed yet, please assign it to me. Thanks

I'm working on it still
